### ISSUE TITLE
Modify tperf.cpp to send data from client to server

### ISSUE THREAD

**Issue by Enjia** [facebookincubator/mvfst#100]
Hi I tried to modify tperf.cpp to enable client to send data to server (POST) rather than the original direction (GET) by imitating the sending logic of class ServerStreamHandler and TPerfServer. As a result, my own TPerfClient derives from several callback classes such as QuicSocket::ReadCallback and  override some callback function. However I found that this kind of modification mode caused some problems. I don't show source code here considering its length. I just want to konw that:
1. If this kind of imitation be a good choice for achieve the goal POST？Because obviously in original tperf.cpp the structure of TPerfServer is a bit more complex than TPerfClient.
2. Do you have any practical advice to realize the POST function in tperf?
Thanks!

**Comment by mjoras** [comment]
It should be simple in principle to reverse the flow.

Right now the way it works is that as soon as the server gets an onTransportReady it creates a stream and then as soon as it gets an onStreamWriteReady it sends data.

You could make a tperf that just does the opposite. Instead of the server creating the stream onTransportReady the client would do it, and then the client would write data onStreamWriteReady.

**Comment by Enjia** [comment]
Hi @mjoras thanks for your advice and I made it last weekend and yes client can send data to server. While I found that if there's no delay in network, the transfer speed is acceptable reaching 800-900Mb/s (BW=1G), once I added delay using command "tc qdisc add dev ens3 root netem delay 40ms loss 0.01%" in client side the speed declined to 30-40Mb/s which seemed like a serious decay.  So have you tried to test tperf in different delay and do you have any idea of why such speed deterioration happened？ Thanks again!

**Comment by Enjia** [comment]
@mjoras Thanks and yes I managed to complete this task.
However there's another tough problem: when I add delay using command "tc qdisc add dev...." between server and client (with pacing=true), there's huge deterioration in transfer speed, and I realize that in such condition BBR actually doesn't work at all, while it does work when there's no time delay for I check the function being called in BBR.cpp. So do you have any idea why that phenomenon happened？ Thanks!
