### ISSUE TITLE
Errors about building mvfst-server

### ISSUE THREAD

**Issue by FakerShy** [facebookincubator/mvfst#105]
D: \ foly \ foly / container / detail / f14table. H (890,1): error c2247: "quic:: quicserverworker:: sourceidentityhash" is not accessible because "foly:: F14:: detail:: objectholder < 72, quic:: quicserverworker:: sourceidentityhash, true >" inherits from "quic:: quicserverworker:: sourceidentityhash" using "private"

**Comment by lnicco** [comment]
@FakerShy thanks for reporting. this is a known issue with folly::F14 
windows builds are unfortunately not a high priority for us at this time, but I will try to monitor this bug and try to get it fixed. 
I'll keep the issue open, please stay tuned.

**Comment by lnicco** [comment]
this should be fixed now. 
could you please rebase and try again ? 
and please reopen this issue if still seeing the same error.
