### ISSUE TITLE
The competition between quic-bbr and cubic

### ISSUE THREAD

**Issue by weiyuxingchen** [facebookincubator/mvfst#106]
As we all know, when tcp-bbr flows coexist with a large number of tcp-cubic flows, there will be a catastrophic speed problem. So,I'd like to ask, have you tried the competition between quic-bbr and cubic? Is quic-bbr better than tcp-bbr in term of competition with cubic?   In other words, what are the differences between quic-bbr and tcp-bbr, and whether they will be upgraded to bbr-v2?

**Comment by yangchi** [comment]
I'd expect same unfaireness when quic-bbr and cubic coexist. And I have seen that in very simplified test of 1 quic-bbr stream and 1 cubic stream in a simulation.

I don't know when we will start to work on bbr v2 in mvfst. It's in our plan but right now we have other priorities.

If you send a Pull Request of BBRv2, we are more than happy to review it.
