### ISSUE TITLE
EchoClient and EchoServer unable to establish connection

### ISSUE THREAD

**Issue by DavidWangW** [facebookincubator/mvfst#11]
I can successfully compile the project on Ubuntu. 18.04,but when I run the sample client I get the following error:
vmtest@vmtest-virtual-machine:~/Documents/ietf_quic/mvfst/_build/build/quic/samples$ ./echo -mode=server -host=127.0.0.1 -port=6666 -colorlogtostderr=true -alsologtostderr=true
I0514 08:35:31.092536 28271 EchoServer.h:80] Echo server started at: [::]:6666

vmtest@vmtest-virtual-machine:~/Documents/ietf_quic/mvfst/_build/build/quic/samples$ ./echo -mode=client -host=127.0.0.1 -port=6666 -colorlogtostderr=true -log_dir="/home/vmtest/Documents/ietf_quic/mvfst/_build/build/quic/samples/" -alsologtostderr=true
I0514 08:36:33.769158 28283 EchoClient.h:127] EchoClient connecting to 127.0.0.1:6666
E0514 08:36:33.771145 28283 EchoClient.h:82] EchoClient error: Connect failed

It seems that the handshake method failed. (ClientHandshake::connect() )
What should I do to make the client and server connect successfully?

**Comment by udippant** [comment]
Can you include the verbose log from both the client and the server?
 i.e. `./echo -mode=server -host=127.0.0.1 -port=6666 -colorlogtostderr=true -alsologtostderr=true --v=10  `

**Comment by DavidWangW** [comment]
@udippant
vmtest@vmtest-virtual-machine:~/Documents/ietf_quic/mvfst/_build/build/quic/samples$ ./echo -mode=client -host=127.0.0.1 -port=6666 -colorlogtostderr=true -log_dir="/home/vmtest/Documents/ietf_quic/mvfst/_build/build/quic/samples/" -alsologtostderr=true --v=10
I0514 09:01:18.038892 28311 EventBase.cpp:117] EventBase(): Created.
I0514 09:01:18.039906 28312 EventBase.cpp:280] EventBase(): Starting loop.
I0514 09:01:18.040313 28312 QuicClientTransport.cpp:50] client created client CID=b1fbc0e40a8a05dc server CID=None peer address=<uninitialized address>
I0514 09:01:18.040407 28312 EchoClient.h:127] EchoClient connecting to 127.0.0.1:6666 
I0514 09:01:18.041589 28312 StateMachine-inl.h:41] Transition from Uninitialized to ExpectingServerHello
I0514 09:01:18.041658 28312 QuicTransportFunctions.cpp:862] Client writing data using scheduler=CryptoAndAcksScheduler client CID=b1fbc0e40a8a05dc server CID=None peer address=127.0.0.1:6666
I0514 09:01:18.041740 28312 QuicPacketScheduler.cpp:487] Wrote crypto frame offset=0 bytesWritten=234 client CID=b1fbc0e40a8a05dc server CID=None peer address=127.0.0.1:6666
I0514 09:01:18.042423 28312 QuicTransportFunctions.cpp:184] Client sent packetNum=0 in space=InitialSpace size=1255 client CID=b1fbc0e40a8a05dc server CID=None peer address=127.0.0.1:6666
I0514 09:01:18.042490 28312 QuicTransportFunctions.cpp:71] Client sent packetNum=0 space=InitialSpace client CID=b1fbc0e40a8a05dc server CID=None peer address=127.0.0.1:6666
I0514 09:01:18.042683 28312 QuicTransportFunctions.cpp:559] Client written crypto and acks data type=Initial packets=1 client CID=b1fbc0e40a8a05dc server CID=None peer address=127.0.0.1:6666
I0514 09:01:18.042752 28312 QuicLossFunctions.h:189] setLossDetectionAlarm setting transmission alarm=99ms method=Handshake outstanding=1 handshakePackets=1 pureAckPackets=0 Client client CID=b1fbc0e40a8a05dc server CID=None peer address=127.0.0.1:6666
I0514 09:01:18.042807 28312 QuicTransportBase.cpp:1974] schedulePathValidationTimeout cancel timeout client CID=b1fbc0e40a8a05dc server CID=None peer address=127.0.0.1:6666
I0514 09:01:18.042855 28312 QuicTransportBase.cpp:1038] Client stopping write looper client CID=b1fbc0e40a8a05dc server CID=None peer address=127.0.0.1:6666
I0514 09:01:18.042981 28312 AsyncUDPSocket.cpp:491] AsyncSocket::handleErrMessages(): recvmsg returned 1
I0514 09:01:18.043046 28312 AsyncUDPSocket.cpp:491] AsyncSocket::handleErrMessages(): recvmsg returned -1
I0514 09:01:18.043131 28312 QuicTransportBase.cpp:274] Stopping read looper due to immediate close client CID=b1fbc0e40a8a05dc server CID=None peer address=127.0.0.1:6666
I0514 09:01:18.043187 28312 QuicTransportBase.cpp:692] Stopping read looper client CID=b1fbc0e40a8a05dc server CID=None peer address=127.0.0.1:6666
I0514 09:01:18.043282 28312 QuicTransportBase.cpp:1000] Stopping peek looper client CID=b1fbc0e40a8a05dc server CID=None peer address=127.0.0.1:6666
I0514 09:01:18.043331 28312 QuicTransportBase.cpp:1025] Client stopping write looper because conn closed client CID=b1fbc0e40a8a05dc server CID=None peer address=127.0.0.1:6666
E0514 09:01:18.043413 28312 EchoClient.h:82] EchoClient error: Connect failed

**Comment by agnosticdev** [comment]
I was able to reproduce this as well with the echo client / server examples:
`./echo -mode=client -host=127.0.0.1 -port=6666 -colorlogtostderr=true -log_dir="/home/agnosticdev/Documents/code/cpp/mvfast/_build/build/quic/samples/logs" -alsologtostderr=true`
![connection_failed_example](https://user-images.githubusercontent.com/7466510/57666866-1ef7aa80-75c7-11e9-96af-f705e7011e94.png)



`./echo -mode=server -host=127.0.0.1 -port=6666 -colorlogtostderr=true -alsologtostderr=true --v=10`

![echo_client_bugfix](https://user-images.githubusercontent.com/7466510/57666652-4ac66080-75c6-11e9-90bf-487ed0d62fa8.png)

```
I0513 21:20:21.171392 14234 EchoServer.h:80] Echo server started at: [::]:6666
I0513 21:20:21.171388 14241 QuicServerWorker.cpp:69] Registered read on worker=0x55fb000d74f0 thread=139644201064192 processId=0
I0513 21:20:21.171394 14240 QuicServerWorker.cpp:69] Registered read on worker=0x55fb000d7210 thread=139644209456896 processId=0
I0513 21:20:21.171360 14236 QuicServerWorker.cpp:69] Registered read on worker=0x55fb000d6680 thread=139644450768640 processId=0
I0513 21:20:21.171360 14237 QuicServerWorker.cpp:69] Registered read on worker=0x55fb000d6960 thread=139644442375936 processId=0
I0513 21:20:21.171406 14242 QuicServerWorker.cpp:69] Registered read on worker=0x55fb000d77d0 thread=139644192671488 processId=0
I0513 21:20:21.171408 14234 EventBase.cpp:280] EventBase(): Starting loop.
I0513 21:20:21.171394 14238 QuicServerWorker.cpp:69] Registered read on worker=0x55fb000d6c20 thread=139644433983232 processId=0
```
It looks like after `resumeRead()` calls out to `AsyncUDPSocket` and nothing else is recorded after that.
```c++
void QuicServerWorker::start() {
  CHECK(socket_);
  if (transportSettings_.pacingEnabled && !pacingTimer_) {
    pacingTimer_ = TimerHighRes::newTimer(
        evb_, transportSettings_.pacingTimerTickInterval);
  }
  socket_->resumeRead(this);
  VLOG(10) << "Registered read on worker=" << this
           << " thread=" << folly::getCurrentThreadID()
           << " processId=" << (int)processId_;
}
```
```c++
void AsyncUDPSocket::resumeRead(ReadCallback* cob) {
  CHECK(!readCallback_) << "Another read callback already installed";
  CHECK_NE(NetworkSocket(), fd_)
      << "UDP server socket not yet bind to an address";

  readCallback_ = CHECK_NOTNULL(cob);
  if (!updateRegistration()) {
    AsyncSocketException ex(
        AsyncSocketException::NOT_OPEN, "failed to register for accept events");

    readCallback_ = nullptr;
    cob->onReadError(ex);
    return;
  }
}
```
Will keep digging.

**Comment by lnicco** [comment]
there looks to be something off with bind. can you try remove the —client and —server arguments from your commands?

**Comment by DavidWangW** [comment]
@lnicco 
![echo](https://user-images.githubusercontent.com/3634265/57673534-edc2bd00-764e-11e9-8f03-a4fdd4798bfe.jpg)

**Comment by agnosticdev** [comment]
After updating the commands to:
Echo Server: `./echo --v=10`
Echo Client: `./echo -mode=client --v=10`

I am now able to see data being echoed on the server side:
```
I0514 05:09:48.316179 25235 QuicTransportBase.cpp:1143] Delivered eof to app for stream=0 client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:51044
I0514 05:09:48.316190 25235 QuicTransportBase.cpp:717] Stopping read looper client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:51044
I0514 05:09:48.316202 25235 QuicTransportBase.cpp:1023] Stopping peek looper client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:51044
I0514 05:09:48.316215 25235 QuicTransportBase.cpp:1043] Server stopping write looper client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:51044
I0514 05:09:48.316227 25235 EchoHandler.h:73] Got len=5 eof=1 total=5 **data=mvfst**
I0514 05:09:48.316241 25235 QuicTransportBase.cpp:1038] Server running write looper thisIteration=1 client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:51044
I0514 05:09:48.316254 25235 QuicTransportBase.cpp:717] Stopping read looper client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:51044
I0514 05:09:48.316267 25235 QuicTransportBase.cpp:1038] Server running write looper thisIteration=1 client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:51044
I0514 05:09:48.316282 25235 QuicTransportFunctions.cpp:865] Server writing data using scheduler=FrameScheduler client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:51044
I0514 05:09:48.316308 25235 QuicWriteCodec.cpp:118] writing frame stream=0 offset=0 data=10 fin=1
```
Client:
```
b90af82c7 peer address=[::1]:6666
I0514 05:09:41.108058 25237 QuicTransportBase.cpp:1979] schedulePathValidationTimeout cancel timeout client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:6666
I0514 05:09:41.108064 25237 QuicTransportBase.cpp:717] Stopping read looper client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:6666
I0514 05:09:41.108070 25237 QuicTransportBase.cpp:1023] Stopping peek looper client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:6666
I0514 05:09:41.108076 25237 QuicTransportBase.cpp:1043] Client stopping write looper client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:6666
mvfst 
I0514 05:09:48.315528 25237 QuicTransportBase.cpp:581] Setting setReadCallback for stream=0 cb=0x7ffcd4996c48 client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:6666
I0514 05:09:48.315577 25237 QuicTransportBase.cpp:717] Stopping read looper client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:6666
I0514 05:09:48.315599 25237 QuicTransportBase.cpp:1038] Client running write looper thisIteration=1 client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:6666
I0514 05:09:48.315615 25237 **EchoClient.h:167] EchoClient wrote "mvfst", len=5 on stream=0**
I0514 05:09:48.315644 25237 QuicTransportFunctions.cpp:865] Client writing data using scheduler=FrameSchedulerWithoutCrypto client CID=db2ee4d1754f2aa7 server CID=400001db90af82c7 peer address=[::1]:6666
I0514 05:09:48.315671 25237 QuicWriteCodec.cpp:118] writing frame stream=0 offset=0 data=5 fin=1

```
Do you want me to put a PR up to switch the echo example on the README?

**Comment by siyengar** [comment]
I have a feeling like it’s something wrong with the binding to the v4 interface on the host. By default we bind to the v6 localhost which is ::1.

Ya please feel free to put up a pr to fix it to v6 localhost.

**Comment by agnosticdev** [comment]
Ahh, yes.  I see it now. It looks like the `client()` takes the `FLAGS_host` argument while the server is started with just `FLAGS_port` and `FLAGS_port`, so the server is then by default binding to ::1.  Thank you!
```c++
if (FLAGS_mode == "server") {
  EchoServer server(FLAGS_port, FLAGS_port);
  server.start();
} else if (FLAGS_mode == "client") {
  if (FLAGS_host.empty() || FLAGS_port == 0) {
    LOG(ERROR) << "EchoClient expected --host and --port";
    return -2;
  }
  EchoClient client(FLAGS_host, FLAGS_port, FLAGS_pr);
  client.start();
} else {
  LOG(ERROR) << "Unknown mode specified: " << FLAGS_mode;
  return -1;
}

```

**Comment by agnosticdev** [comment]
The update above does include passing in a `IPv4` or `IPv6` host argument to the echo server as well as a `README` fix.

**Comment by udippant** [comment]
Addressed on https://github.com/facebookincubator/mvfst/pull/13
