### ISSUE TITLE
problems running echo server

### ISSUE THREAD

**Issue by habt** [facebookincubator/mvfst#112]
I am getting the following output on the server when I try to run the midst client-server

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: getCurrentTime()
          Returns: 8-byte object <00-00 00-00 00-00 00-00>
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#knowing-when-to-expect for details.

GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: getCurrentTime()
          Returns: 8-byte object <00-00 00-00 00-00 00-00>
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#knowing-when-to-expect for details.

How do I fix this?

**Comment by yangchi** [comment]
It's a warning, not an error. I think you can just ignore it.
Just to double check, are you talking about a test case, or the quic/sample/echo client and server?

**Comment by mjoras** [comment]
This shouldn't be an issue anymore, can you you retest with the latest master?

**Comment by habt** [comment]
> It's a warning, not an error. I think you can just ignore it.
> Just to double check, are you talking about a test case, or the quic/sample/echo client and server?

Okay thanks! It's with the echo client and server.
