### ISSUE TITLE
Public Server build file

### ISSUE THREAD

**Issue by piano-man** [facebookincubator/mvfst#122]
After building successfully, which binary in the build directory represents the public server running on fb.mvfst.net:443 ?
If not exactly, which one implements most of the functionality ?
Thanks :)

**Comment by lnicco** [comment]
@piano-man the one running on fb.mvfst.net (for QUIC interop) is based on proxygen so that we can also do HTTP/3 
you'll have to build https://github.com/facebook/proxygen 
and the executable file is called HQ (like HTTP over QUIC)..

**Comment by lnicco** [comment]
the proxygen build pulls this repo as a dependency
