### ISSUE TITLE
Performance numbers?

### ISSUE THREAD

**Issue by psantosl** [facebookincubator/mvfst#124]
Hi,

We'd like to develop a C# wrapper on top of mvfst. Before doing that, we'd like to better understand mvfst performance. Are there any performance figure available? How mvfst compare with TCP and in which scenarios?

Thanks!

**Comment by mjoras** [comment]
Hello!

What kind of performance numbers are you interested in? Single stream continuous throughput? 

We have a tool for this in quic/tools, called "tperf". The defaults are not great though, and it needs some tuning to get right.

I can tell you that in good network conditions on modern Linux, mvfst can achieve > 3Gbps of single stream throughput on commodity server hardware.

When used as the transport for HTTP/3, it is not less performant than TCP + HTTP/2, albeit at a higher per-transaction CPU cost.

**Comment by psantosl** [comment]
Thanks!

Yes, I'd like to understand how it compares to TCP under different scenarios. We'd like to use mvfst as our transport (optional) in our software, and that's why. So, any numbers comparing will be great :)

> We have a tool for this in quic/tools, called "tperf". The defaults are not great though, and it needs some tuning to get right.

Any hints on how to use this?

**Comment by yangchi** [comment]
Example:

```
# Server:
$BUILD_DIR/tperf -congestion=none -gso true --max_cwnd_mss=4294967295 --num_streams=10 &

# Client:
$BUILD_DIR/tperf -mode client -congestion=newreno  -window 256000 -duration=20
```

You can find more params from the quic/tools/tperf.cpp file, or run  $BUILD_DIR/tperf --help

**Comment by yangchi** [comment]
@psantosl : i think we are good to close this? Let us know if there are more you'd like to know or if you run into any problem. Thank you!

**Comment by psantosl** [comment]
Sure! Thank you!
