### ISSUE TITLE
folly::IOBuf : Segmentation Fault 

### ISSUE THREAD

**Issue by piano-man** [facebookincubator/mvfst#125]
(OS :- Ubuntu 18.04 on VirtualBox)
I'm curious about what the probable cause for such an error might be. Is it something that might occur because of the machine I'm running it on or something in the library ?
(I'm executing the example-echo server and sending packets to it through a custom client)

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056370934a731 in folly::IOBuf::cloneOne (this=this@entry=0x0)
    at /mvfst/_build/deps/folly/folly/io/IOBuf.h:1559
1559	    return reinterpret_cast<SharedInfo*>(flagsAndSharedInfo_ & ~kFlagMask);

PC: @     0x56370934a731 folly::IOBuf::cloneOne()
*** SIGSEGV (@0x30) received by PID 29406 (TID 0x7f9996fee700) from PID 48; stack trace: ***
    @     0x7f999894a641 (unknown)
    @     0x7f999898e540 (unknown)
    @     0x56370934a731 folly::IOBuf::cloneOne()
    @     0x56370934b6cb folly::IOBuf::clone()
    @     0x563709140089 quic::samples::EchoHandler::readAvailable()
    @     0x56370922227e quic::QuicTransportBase::invokeReadDataAndCallbacks()
    @     0x563709250a05 quic::FunctionLooper::commonLoopBody()
    @     0x563709250bb3 quic::FunctionLooper::runLoopCallback()
    @     0x563709355ac2 folly::EventBase::runLoopCallbacks()
    @     0x563709356d72 folly::EventBase::loopBody()
    @     0x563709357885 folly::EventBase::loop()
    @     0x5637093598b8 folly::EventBase::loopForever()
    @     0x563709373943 folly::run()
    @     0x7f9998451f74 (unknown)
    @     0x7f9998982669 start_thread
    @     0x7f999815b323 clone
Segmentation fault (core dumped)

**Comment by lnicco** [comment]
hi @piano-man 
this shouldn't happen. 
Would you please post here the exact commands for a repro ?

**Comment by lnicco** [comment]
@piano-man I found this issue that you open and then closed a while back https://github.com/facebookincubator/mvfst/issues/123
and this one looks if not the same stack trace, likely the same root cause. 

can you please add all the commands used to build and run the samples, and any code changes to the repo. Thank you!

**Comment by piano-man** [comment]
I use the standard commands to build the repo i.e.
./build_helper.sh
I then run the server using 
./_build/build/quic/samples/echo -mode=server -host=0.0.0.0 -port=4433

No changes made to the code at all.

However, I do not run into this just on executing the server. Under normal circumstances, the echo server works fine.
It's when I send specific packets from my custom client to it that it runs into this error. I'm just trying to figure out if this is something that's happening because of my machine config or an actual bug in the library.
Thanks :)

**Comment by lnicco** [comment]
awesome! 
Could you then share the code for your custom client or the inout that causes this crash on the echo server?

**Comment by piano-man** [comment]
By input do you mean the pcap file generated ? I wonder if the dump file would help you figure out the cause?

**Comment by piano-man** [comment]
I see. I won't be able to provide the code for the custom client at the moment as it is a part of an ongoing research project. Sorry about that.

I hope this can help a little.

**Comment by piano-man** [comment]
I see, I won't be able to provide the code for the custom client just yet as it is a part of an ongoing research project. Sorry about that.
I hope this pcap can help in some way though :- [dump.pcap](https://drive.google.com/open?id=1GJqstDOBfhJNrM2Fqbq2l2P1nq9SUm9K)

**Comment by piano-man** [comment]
Looking at the packets sent and received on the server side, this is what I could summarize :- 
Packets sent from the client after handshake :-

1. Packet Containing Stream Data frame with {Stream id:4, Stream offset: 0, Payload: "Echo", FinBit: false}
2. Packet Containing Stream Data frame with {Stream id:4, Stream offset: 4, Payload: "", FinBit: true}

The first packet is registered and read normally at the Echo server. The second packet is detected but the error starts from this line in /mvfst/quic/samples/EchoHandler.h:72 :   _"  << " data=" << data->clone()->moveToFbString().toStdString();_"
This in turn calls /mvfst/_build/deps/folly/folly/io/IOBuf.cpp:603:  _"auto tmp = cloneOne();"_
which in turn calls /mvfst/_build/deps/folly/folly/io/IOBuf.cpp:613: _"if (SharedInfo* info = sharedInfo())"_ where the Seg fault finally occurs.

What's interesting is that if I reverse the sequence of the two packets described above, the Echo server responds normally.

**Comment by piano-man** [comment]
Any luck figuring out the cause for this ?

**Comment by afrind** [comment]
Oh, it it maybe the clone() in the INFO log statement calling clone on a nullptr data?  What if you comment out the LOG(INFO) line?

**Comment by piano-man** [comment]
Yes! That does seem to fix it!

**Comment by afrind** [comment]
Fixed by https://github.com/facebookincubator/mvfst/commit/67d15ec8670f0b66860a27eca444a114a6622bb0
