### ISSUE TITLE
Echo Server: Same offset different data

### ISSUE THREAD

**Issue by piano-man** [facebookincubator/mvfst#126]
I was wondering what are the rules that the echo server follows to handle receiving different data for the same offset in a stream ?

Thanks!

**Comment by yangchi** [comment]
Did you get an answer to this?

**Comment by piano-man** [comment]
I've found the behavior to be rather erratic. I haven't exactly been able to figure what rule is used by the streams while reconstructing data. I thought it would be that it would try to fill in the stream in a contiguous manner and retain the data that it receives at a particular position first, but that does not seem to be the case always.

Do you happen to know what rules are followed exactly ?

**Comment by siyengar** [comment]
The EchoServer will not get different data for the same offset, the api will deliver one offset only once. The underlying transport deals with this by discarding data that has already been received for a particular offset.
