### ISSUE TITLE
Speed of tperf in 10Gbps network

### ISSUE THREAD

**Issue by Enjia** [facebookincubator/mvfst#127]
I run tperf in 10Gbps network and the speed is about 2000Mbps or less. Have you tested tperf in such 10Gbps network and what params should be tuned according to such condition? Thanks!

**Comment by yangchi** [comment]
Pretty sure at some point Mvfst will be bounded by CPU on a 10G link. I don't have the exact number. Maybe @mjoras knows that on top of his head.

**Comment by mjoras** [comment]
I've never gotten that close to 10Gbps with tperf with current hardware. The best we can do is probably in the 4-5Gbps range. Most of this is due to kernel copying cost and crypto cost.

@Enjia if you want to saturate a 10Gbps link, you will likely need multiple tperf clients connecting to a single tperf server, as that will be able to utilize multiple CPU cores.

**Comment by Enjia** [comment]
Thanks @yangchi @mjoras BTW, I wonder how to set parameters of your best performance in  4-5Gbps range?

**Comment by yangchi** [comment]
Enable GSO, use a large cwnd limit on server side, large flow contro limit on client side, and set congestion to none, and then increase num_streams param on server side. I think Matt used 10 but you can try different values.

if you know your PMTU value you can also increase the packet size to be able to utilize your PMTU well.

**Comment by yangchi** [comment]
closing this as lack of activity. I guess we answered it OK?

**Comment by Sunsapience** [comment]
> I've never gotten that close to 10Gbps with tperf with current hardware. The best we can do is probably in the 4-5Gbps range. Most of this is due to kernel copying cost and crypto cost.
> 
> @Enjia if you want to saturate a 10Gbps link, you will likely need multiple tperf clients connecting to a single tperf server, as that will be able to utilize multiple CPU cores.

Hi I wonder the word “that” points to the best bandwidth your hardware can offer is 10Gb or the speed under 10Gb circumstance you can reach(4-5Gb)?
