### ISSUE TITLE
Why not use the tag to clone the repositories

### ISSUE THREAD

**Issue by daohu527** [facebookincubator/mvfst#128]
## questions
Because the code base already has thousands of commits, I want to clone only the latest commit by tag, which will save a lot of time to clone the repositories.
https://github.com/facebookincubator/mvfst/blob/20021f0396c3b44a45a936b9c3d8945b13bfbfca/build_helper.sh#L168

Also I noticed that the project will checkout the commit in "build/deps/github_hashes", why not use a tag???

## suggestion
I want to pull the repositories as
```
git clone https://github.com/facebook/folly.git -b v2020.05.04.00 --depth=1 "$FOLLY_DIR"
```

**Comment by lnicco** [comment]
@daohu527 
that is the way it works for facebook opensource projects.
we are in the process of switching to a new build system that would work a bit differently (but still not use tags) 

There is a prototype script in the repo top level directory: `getdeps.sh` 
not sure that would work better for you. 
However, in general we are following guidelines for fb oss projects here

**Comment by lnicco** [comment]
sorry I closed by mistake. 

Something that would help here is downloading an archive and uncompressing it: 
e.g. 
https://github.com/facebookincubator/mvfst/archive/cdcedc50d9e9dc60f43a2cb8f8e67434765b0c80.zip 

however given wheat I mentioned above, that we are going to deprecate the build_helper.sh script, we may not invest in making it faster. 
PRs are welcome :)

**Comment by daohu527** [comment]
@lnicco 
Thank you for your reply, if checkout by the commit there will be no good way to avoid pulling a lot of history commit. 
I wonder if the deps will always the latest success build commit ? I notice the build/deps is update 19 hours ago. Will it update automatically when the deps lib update the commit?

**Comment by lnicco** [comment]
unfortunately there is no guarantee on the maximum distance between the head of a dependent repo and the version referenced here.

we decided to not merge this change. as I said above we are in the (slow) process of deprecating this build script anyway
