### ISSUE TITLE
Doubts about quic client and server mode?

### ISSUE THREAD

**Issue by daohu527** [facebookincubator/mvfst#133]
Hi everyone, I have some questions about mvfst quic implement.  

## question
1. I have run the example "./_build/build/quic/samples/echo" and I found that there is no **push** method in server mode. In my opinion, quic is just a streaming protocol, you can send data on both sides.

2. I also have a doubt that could quic server side push data to client by "Connection ID", because the client's ip address will change, then we can identify the client by "connection ID" and found the changed ip address.

**Comment by lnicco** [comment]
1. `echo` is just a sample app. As a sample, it is there to showcase the API and how to use it. 
It is definitely possible for an endpoint to send data to the other endpoint without necessarily following a request/response semantics. 

2. I believe you are pointing to Connection Migration, which is a feature well described in the RFC https://tools.ietf.org/html/draft-ietf-quic-transport-27#section-9 and that mvfst has a preliminary implementation of. To try it out you can use the `hq` sample binary (again, just a sample app, but a bit more complete than `echo` here) distributed with Proxygen https://github.com/facebook/proxygen

**Comment by CodeIsWorld** [comment]
i have the same question, how to push data from server to client ,if i have streamId

**Comment by lnicco** [comment]
QUIC is connection oriented. 
Once a connection is established and a bidirectional stream is open each side can write on it. 
With mvfst the api is called writeChain()
