### ISSUE TITLE
PTO timeout due to tail packet loss, and the probe packet cannot receive the ack

### ISSUE THREAD

**Issue by qianxuyidian-2018** [facebookincubator/mvfst#134]
I have found a strange problem that when there exists some delays in network resulting in some unacked tail packets because ack-eliciting packets are not acknowledged within the expected period of PTO time, and PTO timer expiration triggers sending extra probe ack-eliciting packet, however, I found after receiver gets these probe packets, there seems exist some troubles parsing probe packets in QuicReadCodec::parsePacket , which leads to consecutive PTO expiration. Do you have any ideas why this could happened? Thanks

**Comment by mjoras** [comment]
What are you using to repro this? Could you share your repro details?

Would it be possible for you to collect a qlog if it was done with a mvfst tool?

**Comment by yangchi** [comment]
I think we probably want to add a section in the Readme to let people know how to collect qlog

**Comment by qianxuyidian-2018** [comment]
I am testing with tperf. I am using the 9c4f0c07f56e0687cb512dc6b9414e36dc1470cc branch committed on April 26, 2020。

I do n’t know how to collect qlog, but according to the VLOG(10) print information, the size of the cloned probe packet is 1254, which is larger than 1252 of the original packet. I think there may be some problems with CloningScheduler.

**Comment by yangchi** [comment]
That does happen from time to time unfortunately. It's a known bug.

Did you use -max_receive_packet_size option when you run tperf?

**Comment by qianxuyidian-2018** [comment]
I did not use the -max_receive_packet_size option.
So has this bug been fixed in the version after April 26, 2020，does it still exist in the latest version?

**Comment by yangchi** [comment]
the bug is still there

**Comment by yangchi** [comment]
by the way, do you see the slightly larger packets not getting acked by peer? Just because it's slightly larger than the packet size, doesn't mean peer won't receive it

**Comment by qianxuyidian-2018** [comment]
What I see is that the receiver can receive a slightly larger probe packet, but cannot parse out the data frame from the packet, and there is no reply ack.
In addition, I used the May 18 version for testing. During the data transmission process, the problem that the PTO timeout times exceeded the limit seems to disappear. But when the handshake packet is lost, there is a probability that the handshake retransmission is unsuccessful.

**Comment by qianxuyidian-2018** [comment]
An error occurred when retransmitting the handshake packet. The vlog information is “No space left in packet to write cryptoFrame header of size: 4, space left=0”.

**Comment by Enjia** [comment]
I found the same problem that with bandwidth=1Gb, server causes 7 times onPTOAlarm with error "Exceeded max PTO", I found that every time server triggers onPTO Alarm it then sends 2 packet (size=1252), and client have received all of them, sends ack with size=1267 but server seems doesn't receives the ack or maybe have errors in parsing acks?
Considering the claim "constexpr uint64_t kDefaultV4UDPSendPacketLen = 1252", is there any problem with size 1267 or larger size that client responses? Thanks!

**Comment by yangchi** [comment]
Hi, we recently fixed the packet size violation (fix in https://github.com/facebookincubator/mvfst/commit/236e046925acbe30b7a387d99aacf3df3f301bbf). Do you mind pulling the latest and try again? thanks.

**Comment by yangchi** [comment]
We fixed it in late July but then I forgot to comment on this issue. Sorry

**Comment by qianxuyidian-2018** [comment]
I tried with the latest version and the problem has been solved. Thanks.
