### ISSUE TITLE
Segmentation fault in folly::IOBuf::prependChain at IOBuf.cpp:589

### ISSUE THREAD

**Issue by piano-man** [facebookincubator/mvfst#135]
If the echo server provided in samples is run and a stream frame is provided as input such that the value for the OFF bit is set as false even when the frame does contain a offset value, it causes a segmentation fault to occur at  

 _IOBuf* otherTail = other->prev\__   (IOBuf.cpp:589)

**Comment by yangchi** [comment]
I'm not sure if i get it. What do you mean "a stream frame is provided as input" ?

**Comment by piano-man** [comment]
The client sends a QUIC packet containing the described stream frame(after successfully completing the handshake)

**Comment by yangchi** [comment]
Do you see the segmentation fault on server side or client side?

**Comment by piano-man** [comment]
The server side. The server is the echo server provided in the samples

**Comment by yangchi** [comment]
I will try to get a repro. Thank you so much for reporting this.

**Comment by yangchi** [comment]
I made a client that would do such and couldn't repro the crash. I see server closed the connection with a Frame format error.

Are you OK to share your client or maybe provide more repro steps? Thank you!

**Comment by yangchi** [comment]
Also, can you paste the full stacktrace? Thank you!

**Comment by piano-man** [comment]
I will be unable to provide the client just yet as it is a part of an ongoing research project.
I analysed the result a little more and observed the following :-
The error only seems to occur if the **Stream frame has the finbit set to true, offset set to a non-zero value, payload is empty and the offbit is set to false**. 
Could you perhaps try this specific case and see if you can repro the crash ?

**Comment by piano-man** [comment]
This is what the stack trace looks like:

$0  folly::IOBuf::prependChain (this=0x7f807c013cc8, iobuf=...)
    at /home/test/mvfst/_build/deps/folly/folly/io/IOBuf.cpp:589
$1  0x000055e1c9935230 in quic::samples::EchoHandler::echo (data=..., 
    id=<optimized out>, this=<optimized out>, this=<optimized out>, 
    this=<optimized out>, this=<optimized out>, this=<optimized out>)
    at /home/test/mvfst/quic/samples/echo/EchoHandler.h:101
$2  quic::samples::EchoHandler::readAvailable (this=0x55e1ca310390, 
    id=<optimized out>)
    at /home/test/mvfst/quic/samples/echo/EchoHandler.h:79
$3  0x000055e1c9a18c76 in quic::QuicTransportBase::invokeReadDataAndCallbacks
    (this=0x7f807c005da0)
    at /home/test/mvfst/quic/api/QuicTransportBase.cpp:784
$4  0x000055e1c9a479e1 in folly::detail::function::FunctionTraits<void (bool)>::operator()(bool) (args$0=false, this=0x7f807c006170)
    at /home/test/mvfst/_build/deps/include/folly/Function.h:416
$5  quic::FunctionLooper::commonLoopBody (this=this@entry=0x7f807c0060f0, 
    fromTimer=fromTimer@entry=false)
    at /home/test/mvfst/quic/common/FunctionLooper.cpp:37
$6  0x000055e1c9a47b7f in quic::FunctionLooper::runLoopCallback (
    this=0x7f807c0060f0)
    at /home/test/mvfst/quic/common/FunctionLooper.cpp:63
$7  0x000055e1c9b84c95 in folly::EventBase::runLoopCallbacks (
    this=this@entry=0x55e1ca30d9c0)
    at /home/test/mvfst/_build/deps/folly/folly/io/async/EventBase.cpp:703
$8  0x000055e1c9b86981 in folly::EventBase::loopBody (
    this=this@entry=0x55e1ca30d9c0, flags=flags@entry=0, 
    ignoreKeepAlive=ignoreKeepAlive@entry=false)
    at /home/test/mvfst/_build/deps/folly/folly/io/async/EventBase.cpp:402
$9  0x000055e1c9b8755e in folly::EventBase::loop (
    this=this@entry=0x55e1ca30d9c0)
    at /home/test/mvfst/_build/deps/folly/folly/io/async/EventBase.cpp:315
$10 0x000055e1c9b88b26 in folly::EventBase::loopForever (
    this=this@entry=0x55e1ca30d9c0)
    at /home/test/mvfst/_build/deps/folly/folly/io/async/EventBase.cpp:538
$11 0x000055e1c9ba1638 in folly::run (ebm=0x55e1ca30bdf0, eb=0x55e1ca30d9c0, 
    stop=0x55e1ca30dc18, name=...)
    at /home/test/mvfst/_build/deps/folly/folly/io/async/ScopedEventBaseThread.cpp:40
$12 0x00007f8094ad46df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
$13 0x00007f8095ef16db in start_thread (arg=0x7f8083fff700)
    at pthread_create.c:463
$14 0x00007f809419188f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by afrind** [comment]
Can you write a transport unit test that repros the crash?  Should be easier than writing a client that can send frames in a particular format.

**Comment by yangchi** [comment]
I'm closing this one since it's very old and we can't repro it. If you still see this happens please open another issue. Thanks.
