### ISSUE TITLE
Duplicate code in client/QuicClientTransport.cpp

### ISSUE THREAD

**Issue by daohu527** [facebookincubator/mvfst#136]
## question
The catch branch has the same processing logic, which can be combined.   
https://github.com/facebookincubator/mvfst/blob/98a0aa44e0ec8ad767eb7b472527f441e682e906/quic/client/QuicClientTransport.cpp#L1397-L1409

## suggestion
```
  } catch (const std::runtime_error& ex) {
    runOnEvbAsync([ex](auto self) {
      auto clientPtr = static_cast<QuicClientTransport*>(self.get());
      clientPtr->closeImpl(std::make_pair(
          QuicErrorCode(ex.errorCode()), std::string(ex.what())));
    });
  } catch (const std::exception& ex) {
    LOG(ERROR) << "Connect failed " << ex.what();
    runOnEvbAsync([ex](auto self) {
      auto clientPtr = static_cast<QuicClientTransport*>(self.get());
      clientPtr->closeImpl(std::make_pair(
          QuicErrorCode(TransportErrorCode::INTERNAL_ERROR),
          std::string(ex.what())));
    });
  }
```

**Comment by yangchi** [comment]
But std::runtime_error clearly doesn't have errorCode() method. We could have introduce another common base for Quic exception types i guess. But honestly I don't see it's such a big deal one way or another. If you send a PR, we are happy to review it.
