### ISSUE TITLE
How to open trace in mvfst?

### ISSUE THREAD

**Issue by lixt** [facebookincubator/mvfst#137]
For this feature "QUIC trace APIs to retrieve deep transport level stats.", how can I turn it on?

**Comment by lnicco** [comment]
hi @lixt, if you look at the code you can see calls to a macro called `QUIC_STATS` for transport events. 
you can see the implementation in `QuicTransportStatsCallback.h` and notice how that macro will give callbacks to a QuicTransportStatsCallback instance, if that gets registered. 
Is this answering your question ?

**Comment by avasylev** [comment]
@lixt  echo sample now has example of logging stats quic/samples/echo/LogQuicStats.h
