### ISSUE TITLE
EchoHandler destructor never called 

### ISSUE THREAD

**Issue by Ellie-fans** [facebookincubator/mvfst#140]
Hello, I am encounting a problem when running mvfst/quic/samples/echo example, the EchoHandler destructor never called, when I go through EchoServerTransportFactory::make I found EchoHandler constructor was called here but destructor was called in ~EchoServerTransportFactory(), but EchoServerTransportFactory is constructed once and destructor never called, how can I solve this problem?

**Comment by sharmafb** [comment]
We don't currently do cleanup in the sample code you're referring to for the sake of simplicity. If you would like to do some memory cleanup, you may modify the onConnectionEnd() and onConnectionError() methods.

**Comment by Ellie-fans** [comment]
Thanks
