### ISSUE TITLE
Internal Error with small_vector in folly

### ISSUE THREAD

**Issue by Enjia** [facebookincubator/mvfst#142]
Hi guys when I run tperf with command ./tperf -mode=server -host=10.99.211.104 -port=6666 -pacing=true -gso=true -congestion=bbr -max_cwnd_mss=860000 -window=65536000 in server side and ./tperf -mode=client -host=10.99.211.104 -port=6666 -pacing=true -gso=true -congestion=bbr -max_cwnd_mss=860000 -window=65536000 -duration=30 in client side under 60ms delay and 20% loss.
I met a problem that client broke out with Internal Error, and finally I found that this was caused by the function named makeSizeInternal in small_vector.h and it threw exception: max_size exceeded in small_vector. I replace excption code with LOG(INFO) << newSize << " " << max_size() << " " << capacity(); and the result is "32768 32767 32767" every time I run tperf, and I found that the value 32768 and 32767 has something to do with function updateLargestReceivedPacketNum in QuicStateFunction.h because after ackState.acks.insert(packetNum), the size of acks increases monotonically until it reaches 32767 and then changes to 0 again in some cases.
So I want to know what reason may cause this problem. Thanks!

**Comment by mjoras** [comment]
The structure we use to store the ACK ranges has a max capacity of 2^16 -1, as it uses a uint16_t to encode the length.

That crash means it tried to overflow that, which means it was trying to write 2^16 -1 ACK ranges. 

Does this reproduce with an unmodified mvfst and tperf? I.e. what is in origin/master?

**Comment by Enjia** [comment]
Yes the version of mvfst I use is mvfst0601(June 1st). I have few question about folly and the size of ack blocks:
1. I wonder why function "emplace_back" in small_vector.h calls "makeSize" with first param being "size() + 1", in light of this I modify the "if" condition "newSize > max_size()" into "newSize > max_size() + 1" in function "makeSizeInternal", it can prevent the overflow, but it is likely to be a improper choice.
2. I assume that although function "updateLargestReceivedPacketNum" in QuicStateFunctions.h perform "ackState.acks.insert(packetNum)", there should be some place that the size of ack blocks should decrease, because it seems to be the reason of small_vector overflow( I use LOG(INFO) to print the size of ackState.acks.size() and it finally reaches 32759 and then makeSizeInternal throw exception causing Internal Error. Do you know what's the relation between size of ack blocks and makeSizeInternal(...) ? And is this phenomenon I just mentioned normal?
Thanks~

**Comment by lnicco** [comment]
sounds like you have a modified version of folly::small_vector, which are likely changing how the data structure works. 

in general, questions on the folly abstractions design are more likely to be answered if you ask on the folly repo
