### ISSUE TITLE
Build error in Macos Catalina

### ISSUE THREAD

**Issue by mohamednibrahim** [facebookincubator/mvfst#143]
Hi there,
I'm trying to build the library on Catalina. I'm using the ./build_helper.sh file which apperantly also written to work on MacOS.
I'm getting the following error code : 
./build_helper.sh: line 178: CMAKE_EXTRA_ARGS[@]: unbound variable

any clue how to solve this error?

**Comment by mjoras** [comment]
Probably just a bug in the shell script. Have you tried following the "getdeps.sh" way to build?

**Comment by hashkash** [comment]
Hi,

I hit a similar issue today. I ran the "get-deps.sh" script which took a while to complete successfully. I think tried the build_helper again but in vain. Seems like the CMAKE_EXTRA_ARGS is not set correctly.

I'm running a 19.6.0 Darwin Kernel Version 19.6.0 with macOS Catalina 10.15.6 and cmake version 3.17.3

Also, the documentation doesn't mention building on a Mac although the script supports it. It would be helpful for users to know that :)

Thanks,
Kash

**Comment by hashkash** [comment]
I managed to successfully build this by switching to commit "884544b4", i.e., one commit before ccache support was introduced.

**Comment by lnicco** [comment]
yes this is in fact a known issue. 
as a quick workaround you can change 
`#!/bin/bash -eu` with `#!/bin/bash` at the top of `build_helper.sh`

**Comment by ShuaiZhao** [comment]
@lnicco removed the '-eu', but still got the follow errors:
`[ 13%] Linking CXX executable QuicIntegerTest
Undefined symbols for architecture x86_64:
  "folly::cold_detail::ColdClass::ColdClass()", referenced from:
      quic::getQuicIntegerSize(unsigned long long) in libmvfst_codec_types.a(QuicInteger.cpp.o)
      quic::QuicInteger::getSize() const in libmvfst_codec_types.a(QuicInteger.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [quic/codec/test/QuicIntegerTest] Error 1
make[1]: *** [quic/codec/test/CMakeFiles/QuicIntegerTest.dir/all] Error 2
make: *** [all] Error 2
`

i am running 10.15.7 Catalina
