### ISSUE TITLE
QUIC client always sets qlog file to '.qlog'

### ISSUE THREAD

**Issue by triplewy** [facebookincubator/mvfst#147]
Currently when running proxygen hq with quic in client mode and setting the `--qlogger-path` flag, proxygen will always write the qlog to `qlogger-path/.qlog`. The documentation states that it is intended to write to `<CID>.qlog` but this doesn't happen.

What's happening is in QuicClientTransport.h, the constructor defaults connectionIdSize = 0, so in the below code snippet, `clientConnectionId` will be an empty vector. https://github.com/facebookincubator/mvfst/blob/8581abeed160bcc1d205aab3e35338746d3fc8b4/quic/client/QuicClientTransport.cpp#L48-L51

Later in QuicClientTransport.cpp when the QuicClient sets its qlogger, it will set dcid = clientConnectionId = '':
https://github.com/facebookincubator/mvfst/blob/8581abeed160bcc1d205aab3e35338746d3fc8b4/quic/client/QuicClientTransport.cpp#L1534-L1542

`setDcid()` does not seem to be called again after that. Thus when we call `FileQLogger::outputLogsToFile`, the dcid will have a value but it will be an empty vector, causing the '.qlog' filename. https://github.com/facebookincubator/mvfst/blob/499b5fb0cebf893da1cc9707fa2bbe8eaf3e6c4e/quic/logging/FileQLogger.cpp#L444-L453

While this can be dealt with from the user's perspective by creating multiple distinct qlog directories when running proxygen client multiple times, it is a bit cumbersome. Especially since other QUIC implementations properly output 'unique' qlogs on each run. I'm not sure what the fix will be but changing QuicClientTransport.h constructor to set `connectionIdSize` to some arbitrary number such as 20 temporarily fixes the issue.

**Comment by yangchi** [comment]
Thank you for reporting this! I also noticed that but haven't had the time to fix it. An easy fix would be to use server cid for setDcid call. A proper fix is to remove the setScid and setDcid APIs from QLogger interface and add group_id support, and use server cid as the group_id for now (that will be broken again when we support CID changes in the middle of a connection).

**Comment by mjoras** [comment]
@yangchi is right of course but I think perhaps the best long term approach for the filename is to use the ODCID selected by the client, which is always random and both sides know, and it never changes, for naming qlog files. It's indeed something we need to fix.

**Comment by rmarx** [comment]
The ODCID approach is probably indeed the best one and the one used by most other implementations as well. 

Not intending to hi-jack this issue with a tangent, but qlog draft-02 will include the QLOGDIR environment variable (https://github.com/quiclog/internet-drafts/issues/51), which is similar to SSLKEYLOGFILE in concept. This is already supported by several implementations (e.g., curl, quiche, quic-go), but not sure it's in mvfst yet. Maybe that could be included as part of this fix as well?

**Comment by afrind** [comment]
We now use the ODCID
