### ISSUE TITLE
confusion about pacer

### ISSUE THREAD

**Issue by LyraWang** [facebookincubator/mvfst#148]
void DefaultPacer::refreshPacingRate(
    uint64_t cwndBytes,
    std::chrono::microseconds rtt) {
  if (rtt < conn_.transportSettings.pacingTimerTickInterval) {
    writeInterval_ = 0us;
    batchSize_ = conn_.transportSettings.writeConnectionDataPacketsLimit;
  } else {
    const PacingRate pacingRate =
        pacingRateCalculator_(conn_, cwndBytes, minCwndInMss_, rtt);
    writeInterval_ = pacingRate.interval;
    batchSize_ = pacingRate.burstSize;
    tokens_ += batchSize_;
  }
  if (conn_.qLogger) {
    conn_.qLogger->addPacingMetricUpdate(batchSize_, writeInterval_);
  }
  QUIC_TRACE(
      pacing_update, conn_, writeInterval_.count(), (uint64_t)batchSize_);
  cachedBatchSize_ = batchSize_;
}

######
Hello, the above code was from quic/congestion_control/pacer.cpp
I don't underdtand why have to add a batchSize_ to tokens_ when refreshPacingRate.
And if I don't add this batchsize to tokens, I found that the actual sendingrate is lower than the theoretical sendingrate which caculated as (pacingWindow / mrtt) in bbr. And the reason sendingrate is lower than the theoretical sendingrate is that the time used to sending packets are not counted in adjustedInterval( which is counted in pacer.cpp :updateAndGetWriteBatchSize).
So, it seems that  adding a batchSize_ to tokens_ in refreshPacingRate has made up to the time loss caused by  writeData. 
But how can this value exactly make up for the time loss, is there any way make pacer more accurate?

The above phenomenon occurs under high bandwidth，like 200-1000mbps

**Comment by yangchi** [comment]
Yes, you are right in the sense that adding batchSize_ to token_ in refreshPacingRate is to make up and make sure BBR is able to reach its desired sending rate. It's quite arbitrary to be honest and you aren't the first person who finds this code confusing.

> And the reason sendingrate is lower than the theoretical sendingrate is that the time used to sending packets are not counted in adjustedInterval( which is counted in pacer.cpp :updateAndGetWriteBatchSize).

Can you elaborate more about this part?  Are you suggesting keep a historic track of the time it takes to write packets to socket, and add that to the adjustedInterval as well? It definitely sounds interesting to experiment.

**Comment by LyraWang** [comment]
Thanks for your answer, I'm trying to add the time consumed by writing data to adjustedInterval. The actual sending rate is close to the theoretical sendingrate now. But I don't know if it will cause any other problems. And I'm still testing it.

My modified code:
...writeData(){
  ...
  uint64_t packetLimit =
      (isConnectionPaced(*conn_)
           ? conn_->pacer->updateAndGetWriteBatchSize(Clock::now())
           : conn_->transportSettings.writeConnectionDataPacketsLimit);
  if(isConnectionPaced(*conn_)){
    conn_->pacer.setLastWriteStartTime(Clock::now());
  }
  ...
}

"setLastWriteStartTime()" is the function added in Pacer, when calculating adjustInterval, use this timepoint instead of scheduledWriteTime.

**Comment by yangchi** [comment]
Thank you @LyraWang . I will also test that.

**Comment by mjoras** [comment]
@LyraWang if you'd like you could also submit a PR if you want, this does seem like an interesting idea.

**Comment by yangchi** [comment]
This is taking longer than we expected. The experiment results are quite mixed. We will need to do more tests.

**Comment by yangchi** [comment]
This is fixed now. Thank you so much!

The suggested change was in https://github.com/facebookincubator/mvfst/commit/8b007886df75f646d0be65a2648fc7add9016b4b. There are two other pacing changes went in at the same time to fix perf thanks to @mjoras :

https://github.com/facebookincubator/mvfst/commit/27af216813d269307439ef60507b5f5c8b90e6e3
https://github.com/facebookincubator/mvfst/commit/eb1b1e65a79fa574e9d4fdbbf1a9828199d59318
