### ISSUE TITLE
Installation error in CentOS

### ISSUE THREAD

**Issue by Enjia** [facebookincubator/mvfst#150]
I try to install folly in CentOS7, and there's a problem: Could NOT find LIBURING (missing: LIBURING_LIBRARY LIBURING_INCLUDE_DIR). Do you have idea how to solve it? Thanks

**Comment by yangchi** [comment]
AFAICT, the io_using dep is well gated in Mvfst: https://github.com/facebookincubator/mvfst/blob/master/quic/server/QuicServerBackendIoUring.cpp#L11

Can you paste more from the error output?
Also this sounds like something you may want to ask in the Folly repo. There is a similar issue opened in Folly repo: https://github.com/facebook/folly/issues/1238

**Comment by lnicco** [comment]
@Enjia if this is an issue with folly, please refer to issues in that repository. 
I am closing this. But if you have something actionable for mvfst please feel free to reopen
