### ISSUE TITLE
How to close bidirectional stream

### ISSUE THREAD

**Issue by Enjia** [facebookincubator/mvfst#152]
Hi I just want to close BidirectionalStream in client side, I know that set param "eof" to True in function writeChain can achieve. Buf if there's any way to close stream? Here is what I have tried in client side:

```
void CloseStream(quic::StreamId streamId)
{
    const quic::QuicClientConnectionState& coonState = *dynamic_cast<const quic::QuicClientConnectionState*>(quicClient_->getState());
    quic::QuicStreamState* stream = coonState.streamManager->getStream(streamId);
    stream->sendState = quic::StreamSendState::Closed_E;
    stream->recvState = quic::StreamRecvState::Closed_E;
    coonState.streamManager->addClosed(streamId); 
    auto itr = coonState.streamManager->closedStreams().begin();
    while (itr != coonState.streamManager->closedStreams().end()) 
    {
        coonState.streamManager->removeClosedStream(*itr);        
        itr = coonState.streamManager->closedStreams().erase(itr);
    }
}
```

But it doesn't work at all, naturally after 1min the timeout occurs because there's no extra data to process:
**QftClient failed read from stream=0, error=LocalError: Idle timeout, Idle timeout**
I wonder if BidirectionalStream should be closed on both server & client side ?

**Comment by yangchi** [comment]
You should never directly changing the sendState and recvState on a QuicStreamState. I think you should never directly change any member on a QuicStreamState. They are handled by stream state machine. I'm actually surprised directly changing them doesn't crash your code later on when the state machine finds the states are wrong.

You can resetStream via QuicSocket API.

**Comment by yangchi** [comment]
Also let me add: reset is for when you don't want the stream any more before data are finished transferring. For normal graceful close, EOF is the way to go. The stream will be closed when all the send bytes, including EOF, are acked by peer, and when all the received bytes, including EOF, are received.

**Comment by jdryan** [comment]
@Enjia -- hopefully that answered your question, let us know if there's more
