### ISSUE TITLE
How to use gdb to debug the project

### ISSUE THREAD

**Issue by Ellie-fans** [facebookincubator/mvfst#153]
Hi, I modeled EchoClient source code and implement a client, but when I debugged the code, an error occured when main function returned. According to the prompt information(double free or corruption problem), it is preliminarily concluded that foly library is the problem. I would like to use gdb to debug the project, but I have no idea where to add the the option -g. I would very appreciate if you replied this

**Comment by udippant** [comment]
If you have the core dump from the crash, you can load the core with gdb.
Alternatively, you can also attach a running process to the gdb `gdb -p <process_id>`.

Let us know if you have further questions about `mvfst`.

**Comment by udippant** [comment]
Closing. Feel free to reopen if you have further questions.
