### ISSUE TITLE
Further exploration of closing stream

### ISSUE THREAD

**Issue by Enjia** [facebookincubator/mvfst#155]
In issue #152 I mentioned that I tried to close stream manually. 

This time I try to use function:
`writeChain(streamId, nullptr, true, false);`
with param data set to nullptr. I wonder if this method have effect on closing stream?

Besides, second question is that if function resetStream will cause data loss for receiver because I find that resetStream can cause 'readError'.

Finally, after sender sets up EOF when calling writeChain, is there any solution to enable receiver also to carry out writeChain so that the stream can be closed successfully on both side ?

Thanks!

**Comment by afrind** [comment]
1. Passing 'eof=true' closes the stream.  Passing nullptr for the data param has no effect on stream state.   The comments in QuicSocket.h could be more explicit here.

2. resetStream can cause data loss.  It will cause the sender to stop retransmitting any data on that stream.

3.  A bidirectional stream is conceptually a pair of unidirectional streams that must be closed separately by each peer.  So sending eof=true will close the send side of the stream, but the receive side must be closed by the peer.  You can call stopSending() or setReadCB(nullptr) (which implicitly sends STOP_SENDING) if you are disinterested in the data the peer is sending.  Usually the peer will send a FIN or RST_STREAM after receiving a STOP_SENDING.
