### ISSUE TITLE
Error in building Ubuntu

### ISSUE THREAD

**Issue by DImuthuUpe** [facebookincubator/mvfst#156]
I'm trying to build mvfst on ubuntu 18.04 by running ./build_helper.sh. To disable tests, I set the -DBUILD_TESTS=OFF. However while building, I get following error. What could be the reason for that?

`
+ cmake -DCMAKE_PREFIX_PATH=/home/dimuthu/mvfst/_build/deps -DCMAKE_INSTALL_PREFIX=/home/dimuthu/mvfst/_build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTS=Off ../..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   iostreams
--   system
--   thread
--   filesystem
--   regex
--   context
--   date_time
--   program_options
--   chrono
--   atomic
-- Found folly: /home/dimuthu/mvfst/_build/deps
-- Found fizz: /home/dimuthu/mvfst/_build/deps
-- Found glog: /usr/lib/x86_64-linux-gnu/libglog.so
-- Found gflags from package config
CMake Error: File /home/dimuthu/mvfst/cmake/mvfst-config.cmake.in does not exist.
CMake Error at /usr/share/cmake-3.10/Modules/CMakePackageConfigHelpers.cmake:312 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:122 (configure_package_config_file)

-- Configuring incomplete, errors occurred!
See also "/home/dimuthu/mvfst/_build/build/CMakeFiles/CMakeOutput.log".
See also "/home/dimuthu/mvfst/_build/build/CMakeFiles/CMakeError.log".
`

**Comment by lnicco** [comment]
@DImuthuUpe the current version of the build script works fine for me on Ubuntu 18.04. 

Would you please share here any local changes you may have to help us repro? thanks

**Comment by DImuthuUpe** [comment]
@lnicco I got a new clone and rebuild on the fresh copy. Seems like the error vanished. Now I can run samples. Thanks

**Comment by lnicco** [comment]
awesome! 
thanks for the update
