### ISSUE TITLE
Performance in high capacity links

### ISSUE THREAD

**Issue by habt** [facebookincubator/mvfst#166]
Hi! I am trying to see the throughput and per-packet RTT performance of mvfst CCAs in links with high capacity (loopback and >3Gbps) by modifying the echo client/server to transfer a large file instead of an input string. I noticed that the achieved throughput for all algorithms seems to be significantly lower than the value achieved by iperf3 (mvfst maxing out around 2 Gbps, while iperf3 shows >10Gbps). How do you get it to a higher bandwidth in high capacity links?

**Comment by habt** [comment]
I've managed to achieve a much higher throughput by increasing the default flow control values. It still is lower than the iperf measured value.

**Comment by habt** [comment]
Reopened this because I noticed it was the combination on the default flow control values and UDP send packet length. But it is still not close to iperf rates. Am i missing other parameters that should be adjusted to get high enough rates to come close to the capacity measured by iperf in high capacity links?

**Comment by xttjsn** [comment]
When you said "mvfst maxing out around 2 Gbps, while iperf3 shows >10Gbps", do you mean for loopback or your high capacity link? If it's the later, what's the capacity of that link? Also, could you share your parameters (if not using the default)? 

Most importantly, could you try using the tperf tool? The echo clien/server isn't built for throughput testing.

**Comment by siyengar** [comment]
Usually loopback has a much larger default mtu so iperf uses the mtu available, however mvfst will use a conservative default internet mtu. You can check a few things:

1. What is your default mtu? Mtu has a significant effect on throughput
2. Are you running the latest kernel which has gso support which mvfst can use
3. Are you using the default Params in the perf testing tool?

Additionally iperf is not encrypted udp, so that’s also a very different test. Encryption has a significant effect on throughput

**Comment by habt** [comment]
I 

> When you said "mvfst maxing out around 2 Gbps, while iperf3 shows >10Gbps", do you mean for loopback or your high capacity link? If it's the later, what's the capacity of that link? Also, could you share your parameters (if not using the default)?
> 
> Most importantly, could you try using the tperf tool? It's basically iperf3 for quic. The echo client/server isn't built for throughput testing.

Tests are mostly for loopback. But the high capacity has a limit of around 10Gbps. When testing on loopback I've reached a value of 10Gbps by using tperf. To achieve this rate I gave 256000 for the tperf window parameter,  and increased the 'kDefaultV4UDPSendPacketLen' and other related values manually to a value around 30000. I did not find a way to change the send packet length value through the tperf parameters

**Comment by habt** [comment]
> Usually loopback has a much larger default mtu so iperf uses the mtu available, however mvfst will use a conservative default internet mtu. You can check a few things:
> 
> 1. What is your default mtu? Mtu has a significant effect on throughput
> 2. Are you running the latest kernel which has gso support which mvfst can use
> 3. Are you using the default Params in the perf testing tool?
> 
> Additionally iperf is not encrypted udp, so that’s also a very different test. Encryption has a significant effect on throughput

If i'm not mistaken the mvfst mtu is the value specified in 'kDefaultV4UDPSendPacketLen'. I've increased the 'kDefaultV4UDPSendPacketLen' to about 30000 and increased the flow control window in tperf to get a large value to get a rate of 10Gbps. The kernel is 4.15. I've overlooked the encryption overhead, but as you said it's effect can be more noticeable in high capacity links. A 10Gbps throughput should be enough for my purposes.

**Comment by yangchi** [comment]
According to the internet GSO support was introduced in 4.18. 

What dose getGSO() return on your machine? https://github.com/facebookincubator/mvfst/blob/master/quic/api/QuicBatchWriter.cpp#L548

**Comment by habt** [comment]
I've upgraded from 4.15 to 5.4, and getGSO() returns 0 in 5.4 as well. In the 5.4 machine, increasing UDPsendpacketlen beyond the default 1252 (tested with 2200) works alright for loopback, but not if I send data over the high-capacity ethernet links. I'm sill using the tperf tool for the test.

**Comment by habt** [comment]
I've now scaled down my bottleneck to 500Mbps using netem. While tperf shows a throughput of up to 1.5Gbps without the traffic shaping, it only reports a maximum of around 290 Mbps when the 500Mbps limit is configured for the shaping.  Any ideas why this is so? I've tried with all the congestion control algorithms.

**Comment by mjoras** [comment]
@habt can you share your tperf parameters?

**Comment by habt** [comment]
Sorry for the late reply. I realized a while ago that my problem was caused because I configured larger delay in my test network, and the receiver window was limiting my throughput. It worked after increasing the limit in the receiver's window.
