### ISSUE TITLE
Build breaks: error: no member named 'Options' in 'folly::EventBase'

### ISSUE THREAD

**Issue by yurivict** [facebookincubator/mvfst#176]
```
/wrkdirs/usr/ports/net/mvfst/work/mvfst-ac33c9e7d31dcb27b38082fd016d2bc3db18c436/quic/server/QuicServer.cpp:103:27: error: no member named 'Options' in 'folly::EventBase'
        folly::EventBase::Options().setBackendFactory(
        ~~~~~~~~~~~~~~~~~~^
```

folly is of the latest released version 2020.09.14.00.

**Comment by yangchi** [comment]
can you paste more from the build log?

**Comment by yangchi** [comment]
Make sure you have this: https://github.com/facebook/folly/commit/3d5e59740c1303a54a9e59e425d84aea3f73d7bb

**Comment by yurivict** [comment]
I use folly-2020.09.14.00.

**Comment by yangchi** [comment]
@yurivict : that's before the revision i pointed out. You need to pull latest folly. We don't maintain a Mvfst tag that matched a building point of Folly tagged version.
