### ISSUE TITLE
Missing initial salt for MVFST_EXPERIMENTAL

### ISSUE THREAD

**Issue by metroid2010** [facebookincubator/mvfst#187]
Hello,
As part of a pentesting project, I find myself decrypting quic packets with wireshark. For that, I need the initial salt for each version of the quic protocol used.
I recently found some packets with hexcode version FACEB00E, which, according to this repo, correspond to version MVFST_EXPERIMENTAL ([line 246 in QuicConstants.h](https://github.com/facebookincubator/mvfst/blob/58da0c35c6a28412172e09bfcef45115d5ad237b/quic/QuicConstants.h#L246))
But this version is not mapped to any [kQuicDraft**Salt in FizzCryptoFactory.cpp](https://github.com/facebookincubator/mvfst/blob/58da0c35c6a28412172e09bfcef45115d5ad237b/quic/fizz/handshake/FizzCryptoFactory.cpp#L25).
Is this version using the default salt, as per the switch in the file above? Can it be assumed this MVFST_EXPERIMENTAL will not be remapped to another salt in the future?

Thanks for the help

**Comment by yangchi** [comment]
I think your reading of the code is correct, it will use salt in the default branch.

> Can it be assumed this MVFST_EXPERIMENTAL will not be remapped to another salt in the future?

MVFST_EXPERIMENTAL as a version may not always exist. And `kQuicDraft23Salt` value may not always exist in the future either. So this can be changed in the future.
