### ISSUE TITLE
Problem about copa dp calculation？？

### ISSUE THREAD

**Issue by NickUESTC** [facebookincubator/mvfst#188]
![copa](https://user-images.githubusercontent.com/25731646/96536234-2a73f880-12c6-11eb-838c-8f046791cbb7.png)
hi，i have a question about copa's dp calculation?
I recently found some big difference in code and paper. 
In code we use lrtt to calculate dp, but in copa's paper author recommended use rtt_standing to calculate dp.  
so i want to know why do we use lrtt instead of rtt_standing ?

**Comment by lnicco** [comment]
thanks for reporting! this is a known difference, and we are testing a fix as we speak. 
@venkatarun95

**Comment by lnicco** [comment]
a fix for this was just landed by @venkatarun95 
in https://github.com/facebookincubator/mvfst/commit/7236d95f36824fa3519c98792de7e9b82a714973

it is gated by the `copaUseRttStanding` transport param that must be set to true 

feel free to reopen the issue for questions
