### ISSUE TITLE
Strange phenomenon when creating streams

### ISSUE THREAD

**Issue by Enjia** [facebookincubator/mvfst#191]
When server calls createBidirectionalStream or createUnidirectionalStream, it must send some data first and then can client triggers onNewBidirectionalStream or onNewUnidirectionalStream. 

However, when client calls createUnidirectionalStream with streamId<=254, it doesn't have to send any data to invoke server's onNewUnidirectionalStream, besides, if client calls createUnidirectionalStream and the streamId created >254, it must send some data to invoke server's onNewBidirectionalStream or onNewUnidirectionalStream.

Do you know why this could happen? Thanks!

**Comment by mjoras** [comment]
I'm surprised it's sending stream frames when you call `createBidirectionalStream` or `createUnidirectionalStream` at all. AFAIK we don't send stream frames to the peer until you actually write to the streams you've created. In fact, we don't have the ability to write zero length stream frames which don't have data and a fin. Are you sure you aren't writing something to the lower numbered stream frames?

**Comment by Enjia** [comment]
I am terribly sorry I made some mistakes leading to this bewildering outcome. Thans again！
