### ISSUE TITLE
Unable to join slack channel

### ISSUE THREAD

**Issue by ssinghaldev** [facebookincubator/mvfst#192]
Hey!

I wish to join this community's [slack channel](https://mvfst.slack.com/). But it seems that I can only log-in (if I have credentials) but can't register for same. Does anybody have any idea why?

Thanks!

**Comment by afrind** [comment]
I sent an invite to the email registered with GH.

**Comment by ssinghaldev** [comment]
Thanks! Joined :-)

**Comment by alishir** [comment]
@afrind I have the same problem.
Would you please send me an invitation?

**Comment by lnicco** [comment]
Here is the updated link: https://join.slack.com/t/mvfst/shared_invite/zt-7ug084te-iMvzkeEdZzN1FFNbobx9Ow

(note, this is a temporary invite -- it rotates every 30 days or so)

**Comment by alishir** [comment]
Thanks a lot.
