### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by aneesh-joshi** [facebookincubator/mvfst#20]
Are there any plans to support Windows?
If not, what steps should be taken to try and compile mvfst for Windows?

**Comment by mjoras** [comment]
> Are there any plans to support Windows?
Not presently, we don't currently have a use case that needs Windows. That being said we are not opposed to accepting PRs for Windows support.

> If not, what steps should be taken to try and compile mvfst for Windows?
We haven't tried, but theoretically it should be possible. The only two dependencies we really have are [fizz](https://github.com/facebookincubator/fizz) and [folly](https://github.com/facebook/folly/), both of which should build on Windows with MSVC. If you can work out how to get the dependencies working then I believe Windows support should be possible.

**Comment by edsburke** [comment]
@mjoras thank you for clarifying this. One quick question, has FB open sourced any mobile wrapper of mvfst? Let's say we want to integrate mvfst into your mobile apps. Thanks.

**Comment by yangchi** [comment]
We haven't. There is no such plan. It's a lot of work to clean up the code with very few known interests out there.

**Comment by aneesh-joshi** [comment]
If I get around to compiling fizz and folly (whose builds seem to be failing), I'll be sure to make a PR.
For the time being, should I leave this issue open for others to see or should I close it?

**Comment by yangchi** [comment]
ye i will close this for now. Thank you!

**Comment by nxrighthere** [comment]
Windows is still not supported?

**Comment by rashiqaj** [comment]
Is windows supported now? Was anyone able to build folly/fizz and then mvst successfully on windows.

**Comment by rashiqaj** [comment]
I am still getting compilation error when I build folly and fizz ,.
vcpkg install folly:x64-windows --head
vcpkg install fizz:x64-windows --head.

Any suggestion pl ?

**Comment by lnicco** [comment]
we have a working windows build in CI here via github actions/workflows. I haven’t had the chance to manually build on a windows system directly but I am interested in looking into your build issue. 

would you please post the exact command you are using to build and the coutput log for the failure? 

my suspect is that by using vcpkg you are installing incompatible versions of folly and fizz, but I’ll need the logs to confirm. thank you!
