### ISSUE TITLE
Understanding the copa update implementation

### ISSUE THREAD

**Issue by habt** [facebookincubator/mvfst#202]
Hello,

In the mvfst implementation Copa increases or decreases the congestion window by a value of ` (ack.ackedPackets.size() * conn_.udpSendPacketLen *
                           conn_.udpSendPacketLen * velocityState_.velocity) /
          (deltaParam_ * cwndBytes_);`. But I noticed that this update calculation is different from the other implementations given in [https://web.mit.edu/copa/](url). I was hoping to understand the reasoning behind the update mechanism used here in mvfst.

Thanks

**Comment by yangchi** [comment]
I think the paper has cwnd in packets, and the addition or reduction in the paper is done per ack.

The code you find in mvfst is done per onPacketAcked call which represents acks more than one packet. 

Basically the paper says, on ack, you change this amount: (velocityState_.velocity) / (deltaParam_ * cwnd in packets)

In our case, onPacketAcked acks ack.ackedPackets.size() amount of packets, thus we should change

ack.ackedPackets.size() * conn_.udpSendPacketLen * (velocityState_.velocity) / (deltaParam_ * cwnd in packets) = (ack.ackedPackets.size() * conn_.udpSendPacketLen * conn_.udpSendPacketLen * velocityState_.velocity) / (deltaParam_ * cwndBytes_)

**Comment by yangchi** [comment]
Does that answer the question?

**Comment by habt** [comment]
Yes, that answers it. Thanks!
