### ISSUE TITLE
did client support 0-RTT?

### ISSUE THREAD

**Issue by xcy19920603** [facebookincubator/mvfst#203]

**Comment by mjoras** [comment]
Yes. Are you trying to use it in code or with a CLI utility?

**Comment by xcy19920603** [comment]
I wanna use it in code, but i don't know how to use it

**Comment by xcy19920603** [comment]
I want to use it in my android apps

**Comment by hyz1021984053** [comment]
when use 0-RTT how to send eraly data? eg:use stream 1?

**Comment by mjoras** [comment]
It's up to the app how to use it. From an API perspective all you need to do is make sure the earlyData is enabled in transport settings. Then you write your data as you would any other data once onTransportReady is triggered.

**Comment by hanidamlaj** [comment]
Marking this issue as closed for now, please feel free to re-open if you'd like to follow-up.
