### ISSUE TITLE
Replacing TCP with QUIC

### ISSUE THREAD

**Issue by omarbelhaj99** [facebookincubator/mvfst#206]
Hello, 

I am currently a third-year student in Electronic Engineering, and as a project, I am trying to implement QUIC protocol using aioquic to replace the current TCP. Is anyone able to mentor me or give me some advice? 

Kind regards

Omar

**Comment by lnicco** [comment]
@omarbelhaj99 thanks for your interest in mvfst. 
However this is a c++ implementation of the QUIC transport and it is unrelated to the aioquic python implementation 

You may find support for that library in the aioquic repo instead
https://github.com/aiortc/aioquic
