### ISSUE TITLE
Does mvfst support Windows 32-bit system compilation？

### ISSUE THREAD

**Issue by ziguang89** [facebookincubator/mvfst#207]
At this time folly does not generally support 32-bit on Windows. There is likely a small subset that will work, however it is entirely untested and there are certain components that will never work on 32-bit Windows.  I would like to ask if mvfst support  32-bit system compilation?  Does mvfst use some components that folly does not support 32-bit windows? Thank you!

**Comment by afrind** [comment]
mvfst should compile on a 32 bit system.  We use it in our mobile apps which all have 32 bit targets.  I'm not sure which folly bits you are referring to, however.  If you can point to the non-win32 folly components, we can check to see if mvfst requires them.

**Comment by afrind** [comment]
Closing for now.  Please reopen if you have further questions.
