### ISSUE TITLE
error in echo server when they are in different ip.

### ISSUE THREAD

**Issue by jialianchen** [facebookincubator/mvfst#209]
hello!i meet a error.
i start the server in 150.109.93.80
``
./_build/build/quic/samples/echo -mode=server
``
it output 
``
I0402 22:29:09.309374 24507 QuicServer.cpp:218] NOT using CCP
I0402 22:29:09.309646 24507 EchoServer.h:78] Echo server started at: [::1]:6666
``
and the i start the client in 118.195.159.89
``
 ./_build/build/quic/samples/echo -mode=client -host=150.109.93.80
``
it output
``
I0402 22:31:28.019632 32740 EchoClient.h:131] EchoClient connecting to 150.109.93.80:6666
E0402 22:31:28.156893 32740 EchoClient.h:85] EchoClient error: Connect failed; errStr=Connection refused
``
i had open all the port ,and i can run successfully in local,could you give me some advice how to slove it?
Thanks for your help!

**Comment by afrind** [comment]
From the log output, it seems the EchoServer started on IPv6 localhost, not 150.109.93.80.

**Comment by jialianchen** [comment]
thanks for your help!
i don`t setting anything,so the EchoServer will default  start  in ipv6 ?

**Comment by lnicco** [comment]
you can add `-host=150.109.93.80` to the server invocation

**Comment by jialianchen** [comment]
thanks,but i use `./_build/build/quic/samples/echo -mode=server -host=150.109.93.80`,
it output 
```
terminate called after throwing an instance of 'folly::AsyncSocketException'
  what():  AsyncSocketException: failed to bind the async udp socket for:150.109.93.80:6666, type = Socket not open, errno = 99 (Cannot assign requested address)
*** Aborted at 1617381693 (Unix time, try 'date -d @1617381693') ***
*** Signal 6 (SIGABRT) (0x1f400000a11) received by PID 2577 (pthread TID 0x7f8b888ee700) (linux TID 2578) (maybe from PID 2577, UID 500) (code: -6), stack trace: ***
(error retrieving stack trace)
Aborted (core dumped)
```
i don`t know the reason that cause the error.

**Comment by lnicco** [comment]
make sure the server has that ip address configured on one of the interfaces with `ifconfig -a` 

but since you seem to be running the client on the same host you can also use `-host=127.0.0.1` on both client and server

**Comment by jialianchen** [comment]
thans for your help!
i want to run  the client on the different host.
in 150.109.93.80
```
$ ifconfig -a
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:1a:36:08:a4  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.22.0.12  netmask 255.255.240.0  broadcast 172.22.15.255
        inet6 fe80::5054:ff:fe11:8531  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:11:85:31  txqueuelen 1000  (Ethernet)
        RX packets 432139  bytes 69284470 (69.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 503470  bytes 250449409 (250.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 112703  bytes 10025249 (10.0 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 112703  bytes 10025249 (10.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
don`t have 150.109.93.80,but all of them is private ip.
```
 $curl ifconfig.me
150.109.93.80
```
it shows that my pubilc ip is 150.109.93.80.

**Comment by afrind** [comment]
Perhaps you are behind a NAT so curling ifconfig.me is telling you an address that doesn't belong to your machine?

**Comment by jialianchen** [comment]
yes ,i am using  cloud servers ,so i behind the NET.
but i still don`t know why i can`t connect the echo server....
could you give me some advice?

**Comment by jialianchen** [comment]
so ,the mvfst's echo server only support in one machine or in the LAN?
it seems can't run in the different ip

**Comment by afrind** [comment]
Of course the server can be used across the internet.  You can only bind it to an address on your machine -- I recommend INADDR_ANY if you are unsure (0.0.0.0 or ::).

Your need to point the client to an IP address that routes to this server, so if it is behind some kind of load balancer with a different IP you need to figure that out. Make sure the load balancer, etc has the UDP port for your server open.  6666 (the default) might be blocked by default.  443 is more likely to be open but you'd still need to check your load balancing configuration.
