### ISSUE TITLE
Develop an app

### ISSUE THREAD

**Issue by salmashukry** [facebookincubator/mvfst#215]
Thanks for the tremendous effort in providing an open-source implementation of QUIC. 

I am in the early stages of integrating an app that uses QUIC. The app requires reports of congestion window size, rtt, packet losses from the transport layer (on the sender side) and requires some authority to change the retransmission protocol incase of a packeet loss (on the receiver side).  My question is:

1- Is it enough to develop my app using the methods of `quic/api` directory, or do I need to change any source code from the other directories?

Also, would you mind providing me with any pointers on how to start? Or refer me to a blog/documentation that can give me hints. 

Thanks for handling my question in an issue, since I was not able to join the slack channel.

**Comment by avasylev** [comment]
Example app for QUIC transport https://github.com/facebookincubator/mvfst/tree/master/quic/samples/echo
For HTTP3 https://github.com/facebook/proxygen/tree/master/proxygen/httpserver/samples/hq
