### ISSUE TITLE
What Protocol Features does mvfast support ? Thx.

### ISSUE THREAD

**Issue by Kiddinglife** [facebookincubator/mvfst#218]
I know it must support rfc 9000. but what about else ? for example, does it support https://datatracker.ietf.org/doc/html/draft-ietf-quic-datagram or more features ?

**Comment by lnicco** [comment]
yes datagram is supported

**Comment by Kiddinglife** [comment]
Thx @lnicco. Actually I found this useful link. but which sheet I should refer to for mvfast? Thx.
