### ISSUE TITLE
compile error: undefined reference to `folly::InlineExecutor::cache'

### ISSUE THREAD

**Issue by psl77586** [facebookincubator/mvfst#22]
toolchain info:
gcc 7.4.0
ubuntu 16.04
cmake version 3.10.0

symbol info:
nm -C libfolly.a|grep folly::InlineExecutor::instance_slow
0000000000000008 b guard variable for folly::InlineExecutor::instance_slow()::instance
0000000000000000 T folly::InlineExecutor::instance_slow()
0000000000000010 b folly::InlineExecutor::instance_slow()::instance
U folly::InlineExecutor::instance_slow()
U folly::InlineExecutor::instance_slow()
U folly::InlineExecutor::instance_slow()
U folly::InlineExecutor::instance_slow()
The symbol of "folly::InlineExecutor::instance_slow()" is visible.

compile info:
c++ -O2 -g -DNDEBUG CMakeFiles/QuicTransportBaseTest.dir/QuicTransportBaseTest.cpp.o CMakeFiles/QuicTransportBaseTest.dir///common/test/TestMain.cpp.o -o QuicTransportBaseTest -Wl,-rpath,/usr/local/lib ../../../../deps/lib/libfolly.a ../libmvfst_transport.a ../../codec/libmvfst_codec_types.a ../../common/test/libmvfst_test_utils.a ../../state/libmvfst_state_stream_functions.a ../../server/libmvfst_server.a ../../../googletest/src/googletest-build/./googlemock/libgmock.a ../../../googletest/src/googletest-build/./googlemock/libgmock_main.a ../../../googletest/src/googletest-build/./googlemock/gtest/libgtest.a ../../../googletest/src/googletest-build/./googlemock/gtest/libgtest_main.a ../../client/libmvfst_client.a ../libmvfst_transport.a ../../congestion_control/libmvfst_cc_algo.a ../../codec/libmvfst_codec_pktrebuilder.a ../../common/libmvfst_looper.a ../../happyeyeballs/libmvfst_happyeyeballs.a ../../state/libmvfst_state_pacing_functions.a ../../state/libmvfst_state_ack_handler.a ../../loss/libmvfst_loss.a ../../state/libmvfst_state_simple_frame_functions.a ../../state/libmvfst_state_qpr_functions.a ../../state/libmvfst_state_functions.a ../../codec/libmvfst_codec_pktbuilder.a ../../state/libmvfst_state_stream.a ../../state/libmvfst_state_stream_functions.a ../../flowcontrol/libmvfst_flowcontrol.a ../../state/libmvfst_state_machine.a ../../codec/libmvfst_codec.a ../../handshake/libmvfst_handshake.a ../../codec/libmvfst_codec_packet_number_cipher.a ../../codec/libmvfst_codec_decode.a ../../codec/libmvfst_codec_types.a ../../libmvfst_constants.a /usr/local/lib/libboost_iostreams.so ../../libmvfst_exception.a ../../../../deps/lib/libfolly.a /usr/local/lib/libboost_filesystem.so /usr/local/lib/libboost_context.so /usr/local/lib/libboost_chrono.so /usr/local/lib/libboost_date_time.so -lpthread /usr/local/lib/libboost_program_options.so /usr/local/lib/libboost_system.so /usr/local/lib/libboost_thread.so /usr/local/lib/libboost_regex.so /usr/local/lib/libboost_atomic.so /usr/lib/x86_64-linux-gnu/libdouble-conversion.so /usr/lib/x86_64-linux-gnu/libgflags.so /usr/lib/x86_64-linux-gnu/libglog.so /usr/lib/x86_64-linux-gnu/libevent.so /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libbz2.so /usr/lib/x86_64-linux-gnu/liblzma.so /usr/lib/x86_64-linux-gnu/liblz4.so /usr/lib/x86_64-linux-gnu/libsnappy.so /usr/lib/x86_64-linux-gnu/libiberty.a /usr/lib/x86_64-linux-gnu/libsodium.so -ldl ../../../fizz_project/src/fizz_project-build/./lib/libfizz.a

error info:
Folly is installed
[ 36%] Built target gmock_main
[ 63%] Built target gmock
[ 81%] Built target gtest
[100%] Built target gtest_main
[ 2%] No install step for 'googletest'
[ 3%] Completed 'googletest'
.............................
[ 6%] Completed 'fizz_project'
[ 7%] Built target fizz_project
[ 8%] Built target mvfst_constants
[ 8%] Built target mvfst_exception
[ 11%] Built target mvfst_codec_types
[ 12%] Built target mvfst_codec_decode
[ 13%] Built target mvfst_codec_packet_number_cipher
[ 15%] Built target mvfst_handshake
[ 16%] Built target mvfst_codec_pktbuilder
[ 18%] Built target mvfst_codec
[ 19%] Built target mvfst_state_machine
[ 20%] Built target mvfst_flowcontrol
[ 21%] Built target mvfst_state_stream_functions
[ 22%] Built target mvfst_state_stream
[ 23%] Built target mvfst_state_qpr_functions
[ 24%] Built target mvfst_state_functions
[ 25%] Built target mvfst_state_simple_frame_functions
[ 26%] Built target mvfst_codec_pktrebuilder
[ 27%] Built target mvfst_looper
[ 30%] Built target mvfst_cc_algo
[ 31%] Built target mvfst_happyeyeballs
[ 32%] Built target mvfst_loss
[ 33%] Built target mvfst_state_pacing_functions
[ 36%] Built target mvfst_transport
[ 37%] Built target mvfst_state_ack_handler
[ 38%] Built target mvfst_client
[ 43%] Built target mvfst_server
[ 45%] Built target mvfst_test_utils
[ 47%] Built target QuicPacketSchedulerTest
[ 47%] Linking CXX executable QuicTransportBaseTest

/home/gcc/gcc-exe/include/c++/7.4.0/bits/atomic_base.h:713: undefined reference to folly::InlineExecutor::cache' ../../../fizz_project/src/fizz_project-build/./lib/libfizz.a(ServerProtocol.cpp.o): In function folly::InlineExecutor::instance()':
/home/mvfst/_build/deps/include/folly/executors/InlineExecutor.h:35: undefined reference to folly::InlineExecutor::instance_slow()' ../../../fizz_project/src/fizz_project-build/./lib/libfizz.a(ServerProtocol.cpp.o): In function std::__atomic_basefolly::InlineExecutor*::load(std::memory_order) const':
/home/gcc/gcc-exe/include/c++/7.4.0/bits/atomic_base.h:713: undefined reference to folly::InlineExecutor::cache' ../../../fizz_project/src/fizz_project-build/./lib/libfizz.a(ServerProtocol.cpp.o): In function folly::InlineExecutor::instance()':
/home/mvfst/_build/deps/include/folly/executors/InlineExecutor.h:35: undefined reference to `folly::InlineExecutor::instance_slow()'

who could give me some suggest about this question?Tks very much!

**Comment by aneesh-joshi** [comment]
Having a similar error while building.

**Comment by psl77586** [comment]
> Having a similar error while building.
I use the parameter “-Wl,--whole-archive  --no-whole-archive” to fix the problem.
such as:
 target_link_libraries(
    echo PUBLIC
    -Wl,--whole-archive
    Folly::folly
    -Wl,--no-whole-archive
   ....................
you can have a try.

**Comment by aneesh-joshi** [comment]
@psl77586 
Where should this be put as an argument?

**Comment by udippant** [comment]
Apologies for the issue. https://github.com/facebookincubator/mvfst/commit/97a2ccc4ae4c82d3b0af0689a0f0367881f8dfe8 should fix it.

**Comment by aneesh-joshi** [comment]
@udippant 
Thanks!
It built successfully and passed all the tests on my end.
