### ISSUE TITLE
Invalid use of Packet Number

### ISSUE THREAD

**Issue by sedrubal** [facebookincubator/mvfst#240]
We ran measurements with large files (10 MiB) using a [modified](https://github.com/sedrubal/quic-interop-runner/tree/sat) version of the [QUIC-Interop-Runner](https://github.com/marten-seemann/quic-interop-runner/) and ran some analysis. According the following plots, it seems that mvfst is using random but fixed packet numbers for an entire transfer of the 10 MiB file using QUIC:

![](https://interop.cs7.tf.fau.de/plots/mvfst_lsquic_G_time_packet-number_plot.png)

More plots:

- https://interop.cs7.tf.fau.de/plots/mvfst_msquic_G_time_packet-number_plot.png
- https://interop.cs7.tf.fau.de/plots/mvfst_ngtcp2_G_time_packet-number_plot.png
- https://interop.cs7.tf.fau.de/plots/mvfst_picoquic_G_time_packet-number_plot.png
- https://interop.cs7.tf.fau.de/plots/mvfst_quiche_G_time_packet-number_plot.png

In each plot you can see the packet number over time according to the pcap trace for 10 transmissions.

If I understand [RFC 9000](https://datatracker.ietf.org/doc/html/rfc9000#section-12.3) correctly, this is not allowed:

>  “Packet numbers [. . .] start at packet number 0. Subsequent packets [. . .] MUST increase the packet number by at least one. [. . .] A QUIC endpoint MUST NOT reuse a packet number [. . .] in one connection.”

More measurement results and the pcaps / qlogs can be found here: https://interop.cs7.tf.fau.de/

**Comment by mjoras** [comment]
This is not a violation of the spec and in fact mvfst does this deliberately to ensure that implementations aren't making assumptions about packet numbers.

> Packet numbers [. . .] start at packet number 0

This cannot be interpreted to mean that an endpoint MUST send a packet number starting at 0. To illustrate why simply consider the case of packet loss: if an endpoint sends packet number 0 and it is lost in the network, the packet number it sends next MUST be > 0. An arbitrary amount of packet loss can be assumed in this case, and thus an endpoint must be able to handle receiving an arbitrarily large packet number as the first packet number from the peer endpoint.

**Comment by sedrubal** [comment]
That's true, but aren't you violating against this:

> Subsequent packets sent in the same packet number space MUST increase the packet number by at least one.

**Comment by mjoras** [comment]
@sedrubal where are you seeing packet numbers not monotonically increasing? Mvfst always increments by at least 1 and never repeats.

**Comment by sedrubal** [comment]
The plot shown above suggests it. The script I use to generate the plot is written in python. The code to extract the packet numbers is similar to this:

```python
import pyshark
capture = pyshark.FileCapture(input_file="./trace_node_right.pcap", display_filter='ip.src == 193.167.0.100 && quic', disable_protocol='http3')
packets = list(capture)
packet_numbers = [l.packet_number for l in p.get_multiple_layers('quic') for p in packets]
print(all(pkn == packet_numbers[0] for pkn in packet_numbers))  # -> True
```

You can use [this pcap file](https://interop.sedrubal.de/logs/logs_sat_2021-11-07/mvfst_mvfst/goodput/5/sim/trace_node_right.pcap).

**Comment by mjoras** [comment]
@sedrubal that pcap link doesn't load.

**Comment by mjoras** [comment]
Nevermind, got it to load. This pcap doesn't have decrypted QUIC packets, so of course it can't parse the real packet numbers. You can see from the qlogs in that test that the packet numbers are working as expected.

**Comment by sedrubal** [comment]
You're right, I'm sorry. The plot above looks like constant packet numbers, because the packet numbers are incredibly high and the plot starts at 0. So everything is fine. Thanks for your explanation :wink:
