### ISSUE TITLE
Some questions about Copa

### ISSUE THREAD

**Issue by bluestarx** [facebookincubator/mvfst#241]
It's a very interesting idea for Copa to update cwnd and sending rate based on queuning delay estimation. I've read the paper of Copa and Facebooks's testing result (https://web.mit.edu/copa/#facebook), it achieved significant improvements in goodput and RTT, especially for worst connections. But I came up with some questions while reading the paper and mvfst implementation, and seek for help here:
1. Is Copa working well in network with shallow buffer or large RTT-jitter scenarios?  According to the paper, cwnd (and corresponding sending rate) is updated based on queuing delay estimation (queuing_delay = RTTstanding - minRTT). However, target rate = 1/(delta * queding_delay), so little jitter in RTT may result in large variantion in target rate, if RTT changes rapidly and frequently, could Copa deal with such cases and estimate an accurate target rate? In shallow buffer network, if the buffer is smaller than 1/delta packets, will Copa bring massive packet loss?
2. Since target rate is estimated based on queding delay, if the estimated target rate exceeds bandwith, how will Copa performs?
3. The delta param is the key for Copa's co-existence with Cubic. I found it's difficult to figure out delta for different scenarios. It looks like mvfst uses a constant value (maybe 0.04?) instead of AIAD for delta, will that works well with Cubic?

**Comment by jbeshay** [comment]
As described in the blog post, Copa is currently used for sending Facebook live video streaming data from mobile devices. We don't have additional production data about the performance of Copa in specific situations at the moment. However, the conditions you mention should be straightforward to reproduce using network emulation and test with `hq` command line tool in this repo.

P.S. This 2021 paper from the authors of Copa has some interesting results about its performance too: https://dl.acm.org/doi/10.1145/3452296.3472912
