### ISSUE TITLE
fmt not installed when running install.sh

### ISSUE THREAD

**Issue by dbaldassi** [facebookincubator/mvfst#247]
Hi,

When I run the install.sh script to install mvfst, the fmt lib is not installed along folly, fizz and mvfst.
So, when I add a ``require(mvfst)`` in a cmake project, it just fails because fmt is not found.
Is it intended ? Did I mis-configured something ?

**Comment by jbeshay** [comment]
Yes, this is intentional. Actually, installing mvfst only installs mvfst. folly/fizz/fmt libraries are not installed. These have to be separately installed/added.

**Comment by dbaldassi** [comment]
ok, thank you.
I was asking because folly and fizz were installed. 
Only fmt was missing
