### ISSUE TITLE
Fail to write datagram

### ISSUE THREAD

**Issue by dbaldassi** [facebookincubator/mvfst#249]
Hi,

I'm trying to use the datagram extension.
I have enable the datagram setting in the transport settings on both client and server like this : 
```cpp
quic::TransportSettings settings;
settings.datagramConfig.enabled      = true;
settings.datagramConfig.readBufSize  = 2048;
settings.datagramConfig.writeBufSize = 2048;

transport->setTransportSettings(settings);
transport->setDatagramCallback(_handler);
```

Then I try to send a message by calling the `writeDatagram` method but it is always failing.
The issue seems to be because the maxWriteFrameSize is always 0.

```cpp
auto state = transport->getState();
auto maxWriteFrameSize = state->datagramState.maxWriteFrameSize; // always == 0
```

Did I miss something in the configuration to write datagrams ?

**Comment by kvtsoy** [comment]
echo client/server in samples supports datagrams, maybe that code will help?
echo --mode server --use_datagrams=true
echo --mode client --use_datagrams=true
