### ISSUE TITLE
How to choose QUIC version

### ISSUE THREAD

**Issue by wtao0221** [facebookincubator/mvfst#252]
Hi,

Is there any option to choose QUIC-v1 rather than the FB-draft version of QUIC?

**Comment by kvtsoy** [comment]
Yes, you can use setSupportedVersions():  https://github.com/facebookincubator/mvfst/blob/main/quic/client/QuicClientTransport.h#L125

**Comment by kvtsoy** [comment]
Also on server, setSupportedVersion(): https://github.com/facebookincubator/mvfst/blob/main/quic/server/QuicServer.h#L112

**Comment by wtao0221** [comment]
Thanks! It worked!
