### ISSUE TITLE
about encrypt/decrypt path in mvfst

### ISSUE THREAD

**Issue by wtao0221** [facebookincubator/mvfst#253]
Hi,

I am going through mvfst's source code. I am wondering where the encrypt/decrypt happens in the code.

(Please correct me if I am wrong.) So basically in my understanding, there are 2 parts, one is that application writes data to the stream buffer, bound to one QUIC connection, the other one is that QUIC writes the buffer to the FD (i.e., network). The receive path works in a similar way.

Does the encrypt/decrypt happen in the first part or the second? Or is my understanding wrong?

**Comment by mjoras** [comment]
QUIC packets are encrypted individually, so it has to be done shortly before writing to the network by necessity.

**Comment by mjoras** [comment]
E.g. https://github.com/facebookincubator/mvfst/blob/main/quic/api/QuicTransportFunctions.cpp#L374

**Comment by wtao0221** [comment]
Thanks. BTW, where is the API on choosing cipher suite?
