### ISSUE TITLE
How to turn on IPv4 as the default IP layer?

### ISSUE THREAD

**Issue by wtao0221** [facebookincubator/mvfst#254]
Hi,

It seems that IPv6 is the default IP layer? So how can I turn on IPv4 as the default client IP layer?

**Comment by kvtsoy** [comment]
You can specify whatever address you want.
On client: https://github.com/facebookincubator/mvfst/blob/main/quic/client/QuicClientTransport.h#L90
On server: https://github.com/facebookincubator/mvfst/blob/main/quic/server/QuicServer.h#L46-L52
