### ISSUE TITLE
how to deploy the load balancer and how will it work?

### ISSUE THREAD

**Issue by huowa222** [facebookincubator/mvfst#264]
i see the code "setHostIdBitsInConnId" which mean extracting the process id from connection id, as i know, it is used for generating routing CID in load balancer. how does the load balancer deploy and work? does it work in L4 layer like LVS.

**Comment by huowa222** [comment]
Does the CID generated on server side?

**Comment by afrind** [comment]
In our deployment, the server that terminates the QUIC connection sets its host ID using this API:

https://github.com/facebookincubator/mvfst/blob/main/quic/server/QuicServer.h#L160-L164

The L4 load balancer (katran) and the server both know the format of the connection IDs, and katran instances matinain a map from the host ID to the real IP address of the QUIC server.

https://github.com/facebookincubator/katran/blob/main/katran/lib/bpf/balancer_kern.c#L636
