### ISSUE TITLE
Can't find tperf in _build

### ISSUE THREAD

**Issue by alexj0l** [facebookincubator/mvfst#282]
Hi community,

I've built the mvfst and all tests are passing, but I am unable to find `tperf` under `_build`. 
```
ubuntu@srv: ~/quics/mvfst$ find . -name 'tperf'
./quic/tools/tperf
```
Can someone help me with that?
Thanks

**Comment by lnicco** [comment]
good catch, it looks like the CMake file is missing the install() directive. I'll fix it internally and it'll eventually sync here on github. 

In the meantime you can use the following patch: it will install tperf in `_build/mvfst/bin/tperf` 
```
diff --git a/quic/tools/tperf/CMakeLists.txt b/quic/tools/tperf/CMakeLists.txt
index 26290c0b..f394bfa5 100644
--- a/quic/tools/tperf/CMakeLists.txt
+++ b/quic/tools/tperf/CMakeLists.txt
@@ -34,3 +34,11 @@ target_link_libraries(
   ${GFLAGS_LIBRARIES}
   ${LIBGMOCK_LIBRARIES}
 )
+
+install(
+  TARGETS tperf
+  EXPORT mvfst-exports
+  ARCHIVE DESTINATION ${CMAKE_INSTALL_DIR}
+  LIBRARY DESTINATION ${CMAKE_INSTALL_DIR}
+)
```
