### ISSUE TITLE
Applying mvfst to live streaming

### ISSUE THREAD

**Issue by lgs96** [facebookincubator/mvfst#296]
Hi, I'm recently studying on applying mvfst QUIC for live streaming application.

Transport protocol for live streaming such as google congestion control in webRTC directly utilize bitrate, which can be interpreted to the video encoding quality.

However, packet-level congestion control such as Copa in mvfst is hard for me to apply on live streaming directly.

Is there API or tips to implement live streaming system with mvfst Copa?

**Comment by jbeshay** [comment]
WebRTC congestion control works differently from QUIC congestion control, so it can't be directly mapped to Copa or any other existing CCA implementation in mvfst.

You would probably be interested in the Media Over Quic (MoQ) work group at the IETF (https://datatracker.ietf.org/group/moq/about/). Some of the discussions there cover using QUIC for streaming media.

I will go ahead and close there issue, but feel free to open it if you have follow up questions.
