### ISSUE TITLE
Provide tagged releases?

### ISSUE THREAD

**Issue by ZhongRuoyu** [facebookincubator/mvfst#301]
Hi! [Homebrew](https://brew.sh/) maintainer here. It is noticed that [fbthrift](https://github.com/facebook/fbthrift) is now a dependent of mvfst. However, mvfst does not provide any tagged releases, which makes it not very easy for downstream packagers to ship it and build its dependents. Would mvfst maintainers provide weekly tagged releases, like [folly](https://github.com/facebook/folly/tags), [fizz](https://github.com/facebookincubator/fizz/tags), [fbthrift](https://github.com/facebook/fbthrift/tags), and many other Facebook/Meta C++ projects do? Thanks!

**Comment by carlocab** [comment]
See also https://github.com/facebookexperimental/edencommon/issues/2 for a related request.

**Comment by jbeshay** [comment]
Thanks for bringing this up. I have enabled weekly tags similar to the other repos you mentioned. They should start showing up by the end of this week. I will keep this open until the first tag shows up.

**Comment by jbeshay** [comment]
The first tag was created a couple of days ago.
