### ISSUE TITLE
MacOS Mojave 10.14 build: mvfst_mock_socket library not found

### ISSUE THREAD

**Issue by jsquyres** [facebookincubator/mvfst#4]
It looks like cac86697058a00666c5c9f09c7a2ce907b156458 removed the mvfst_mock_socket library.  Attempting to build at the HEAD on MacOS Mojave 10.14 currently results in:

```
...
[ 78%] Built target HandshakeLayerTest
[ 80%] Built target MacroTest
[ 81%] Built target QuicLossFunctionsTest
[ 82%] Built target echo
[ 83%] Built target QuicServerTransportTest
[ 84%] Linking CXX executable QuicServerTest
ld: library not found for -lmvfst_mock_socket
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [quic/server/test/QuicServerTest] Error 1
make[1]: *** [quic/server/test/CMakeFiles/QuicServerTest.dir/all] Error 2
make: *** [all] Error 2
```

FWIW: If I build at 4ed2963 (i.e., the commit before cac86697058a00666c5c9f09c7a2ce907b156458), I get other MacOS linker errors (which is presumably what cac86697058a00666c5c9f09c7a2ce907b156458 was fixing).

**Comment by siyengar** [comment]
Fix coming up

**Comment by siyengar** [comment]
https://github.com/facebookincubator/mvfst/commit/57aca364ae180e89ffc6dcc008dc51ba987a70f5 Should fix this issue

**Comment by jsquyres** [comment]
@siyengar I confirm that if I rebase #3 on top of current HEAD (ad12bcc19ebbc15ff63a7331120bef2cbd1384c8, which includes 57aca364ae180e89ffc6dcc008dc51ba987a70f5), the problem is, indeed, resolved.  Thank you!
