### ISSUE TITLE
How to transfer files between client and server

### ISSUE THREAD

**Issue by Enjia** [facebookincubator/mvfst#61]
Hi, I run the build_helper.sh successfully and build the sample client and server. However I don't know how to transfer files between client and server? Thanks!

**Comment by lnicco** [comment]
the easiest option to transfer files using mvfst is to use a webserver.
try https://github.com/facebook/proxygen 

build the project with `build.sh -q`
and then start the hq server 
`_build/proxygen/httpserver/hq --mode=server --static_root=/<files_directory>`
and fetch files with 
`_build/proxygen/httpserver/hq --mode=client --outdir=/<output_directory>` --path="/<filename>"

**Comment by yangchi** [comment]
By file transfer do you mean upload or download from client's point of view? Or something more complex?
As Luca suggested, going with hq server in Proxygen is likely the easiest option for downloading files.
If you don't want to use http, just quic, you can probably modify the sample client and sample server so that server handler can read from a file and send it back to client as a stream data? This really depends on what exactly you want to achive. Nevertheless, you will need to write some code to interact with filesystems and read/write files.

**Comment by Enjia** [comment]
thanks guys I have built the proxygen with http3. BTW can proxygen transfers files both from client to servers and server to client(upload and download in one side ) ?Thanks!

**Comment by afrind** [comment]
You can upload using the HTTP POST method.

hq --mode=client --body=<filename>

**Comment by Enjia** [comment]
Here’s some problems I encountered when I run the commands as you hint:

1.When I run command such as：
_build/proxygen/httpserver/hq --mode=server --static_root=/<files_directory>
should I specify the parameters “key” and “cert”? And where to get or how to produce “key” and “cert”?

2.The explanation of “--path” in source code is “url-path to send the request to”, could you please show me an example of the “path”? Does it looks like “/home/test/…” or “https://www.example.com”?

3.When I run the command ”/hq --mode=client --outdir=/home/data/test --path=/home/test/example.txt”, I found that an error occurred saying “SampleHandlers.h906 Invalid URL: cannot open requested file. Path:/home/test/data/example.txt”; meanwhile, after running hq --mode=server --static_root=/home/test/data”, client indicated the message “CurlClient.cpp 265 Got EOM”. 

Do you have any idea of this kind of error? Thanks again for your favor!

**Comment by Enjia** [comment]
Thanks! but I have another issue when running command "hq --mode --body=<filename>", that I have no idea of the destination path that server preserve the file so I can't find my initial file transferred from client. Is there something important such as parameters of path I missed to appoint?  Thanks again for your favor!

**Comment by afrind** [comment]
The server doesn't have a handler to save a file anywhere, but you can write one.  See SampleHandlers.h for how handlers are implemented.  You will define your endpoint (eg: the path you will POST to) and how to derive a filename from there.  Then you can open a file and write the body as it arrives -- all disk I/O should be dispatched to another threads to prevent blocking other network I/O operations in the thread that receives the callbacks.

**Comment by Enjia** [comment]
I got it. I managed to set up the server and client and got test.txt from test-server in the same machine with command :
/hq --mode=server --static_root=/home/data/test-server
/hq --mode=client --outdir=/home/data/test-client  --path=http://test-server/text.txt, however, when server and client were settled in different machines, such as:
/hq --mode=server --static_root=/home/data/test-server
/hq --mode=client --outdir=/home/data/test-client  --host=192.168.33.70 (IP address of server) --port=6666 --outdir=/home/data/test-client --path=http://test-server/text.txt
server showed the message as follows:
16:58:26.206205 32392 HQClient.cpp 61 HQClient connecting to 192.168.33.70:6666
16:58:26.206205 32392 HQClient.cpp 61 HQClient failed to connect, error=Connect failed, msg=Connection refused
Could you please point out how to connect correctly between server and client deployed in different machines? Thanks

**Comment by lnicco** [comment]
QUIC is built on top of UDP. and in your logs looks like hq is using the default port we assigned that is 6666. 
there may be a firewall blocking UDP traffic to and from port 6666. you can pass —v=4 to the client to see more debug output. 

a couple minor fixes to your commands: 
the server does not need the path argument; the path does not need the http://<host> part, just /test.txt will do

**Comment by Enjia** [comment]
But what I found strange is when I run command like “/hq --mode=client --outdir=/home/data/test-client --path=/text.txt” without prefix “http//” the server indicated that "SampleHandler.h:906 Invalid URL: cannot open requested file. Path:/home/data/text.txt". BTW, what does  abbreviation of "EOM" means for I often see it in the output of client. Thanks again

**Comment by afrind** [comment]
EOM means ‘end of message’.  The scheme component of the URL ‘http://’ does not need to be passed to the command

**Comment by Enjia** [comment]
Thanks so much.

 I managed to transfer files between two machines. Nowadays I skimmed through the source code of Proxygen and I am especially confused about a key process in HQClient.cpp that how does client write message into output file? 

I notice that there is a bool variable named "canWrite" associated to saveResponseToFile in HQClient.cpp, right before the code line "client->sendRequest(txn)", I think canWrite is just a signal indicating whether to write or not into output file, and the function "sendRequest( )" is defined in CurlClient.cpp and which further calls function "sendBodyFromFile" that also defined in CurlClient.cpp (I bet you are more clear about the code structure and relationships between these functions). 

After tracing the function "sendBodyFromFile" I gradually get lost because I can't figure out how to write messages into output file in client.......

Meanwhile I also found a funtion named "onBody" in CurlClient.cpp and it seems to carry out the "write" command, unfortunately I still unable to understand the logic of writing. Could you please help me get out of this swamp?

**Comment by afrind** [comment]
> help me get out of this swamp?

I'm reminded of Yoda from "The Empire Strikes Back":

Swamp?  My home this is!

---

CurlClient::saveResponseToFile sets up outputStream_ to point to the specified file instead of std::cout.

CurlClient::onBody is called when a part of the body is received from the server.  It always writes it to outputStream_, which is either std::cout or a file, per above.

**Comment by Enjia** [comment]
I'm sorry for the word "swamp" that may lead to your misunderstanding. Swamp do not refer to your code repository, the structure and logic of Proxygen and mvfst are awesome indeed. That word stands for my mind that doesn't get hang of the whole mechanism of Proxygen during such short time, it is the dilemma in understanding the codes that “swamp” describes. Anyway thanks for your patience!

**Comment by afrind** [comment]
No offense taken.   It's not a straightforward pattern to be sure.  I'm closing this one out for now, but feel free to reopen or open another issue if you have additional questions.  Good luck!
