### ISSUE TITLE
Echoserver does not use folly::EventBase

### ISSUE THREAD

**Issue by pfeatherstone** [facebookincubator/mvfst#67]
The example echo server in Echoserver does not require folly::EventBase.
You can hang the server with a simple 
`while(1) usleep(1000000); `

Though one could do better of course.
I imagine folly::EventBase is left over from a very early implementation

**Comment by yangchi** [comment]
The EchoServer uses EVB to do one thing: to loop forever: https://github.com/facebookincubator/mvfst/blob/master/quic/samples/echo/EchoServer.h#L86

The QuicServer creates evbs used by Quic transports internally: https://github.com/facebookincubator/mvfst/blob/master/quic/server/QuicServer.cpp#L89
