### ISSUE TITLE
Ubuntu1604  build issues

### ISSUE THREAD

**Issue by weiyuxingchen** [facebookincubator/mvfst#75]
Thanks for your reply. Some questions no longer appear, but there are still the following questions:

make -j 4
[ 1%] Performing update step for 'googletest'
[ 2%] Built target mvfst_bufutil
[ 3%] Built target mvfst_constants
[ 3%] Performing configure step for 'googletest'
[ 4%] Built target mvfst_exception
loading initial cache file /home/h3c/ywc/mvfst/_build/build/googletest/tmp/googletest-cache-RelWithDebInfo.cmake
[ 5%] Built target mvfst_looper
-- Configuring done
[ 7%] Built target mvfst_codec_types
-- Generating done
-- Build files have been written to: /home/h3c/ywc/mvfst/_build/build/googletest/src/googletest-build
[ 8%] Performing build step for 'googletest'
[ 9%] Built target mvfst_codec_decode
[ 36%] Built target gmock_main
[ 63%] Built target gmock
[ 81%] Built target gtest
[100%] Built target gtest_main
[ 10%] Built target mvfst_codec_packet_number_cipher
[ 10%] No install step for 'googletest'
[ 10%] Completed 'googletest'
[ 11%] Built target googletest
Scanning dependencies of target PacketNumberTest
Scanning dependencies of target QuicConnectionIdTest
Scanning dependencies of target QuicIntegerTest
[ 14%] Built target mvfst_handshake
[ 14%] Building CXX object quic/codec/test/CMakeFiles/QuicConnectionIdTest.dir/QuicConnectionIdTest.cpp.o
[ 15%] Built target mvfst_codec_pktbuilder
Scanning dependencies of target FizzPacketNumberCipherTest
[ 16%] Building CXX object quic/codec/test/CMakeFiles/QuicIntegerTest.dir/QuicIntegerTest.cpp.o
[ 16%] Building CXX object quic/codec/test/CMakeFiles/PacketNumberTest.dir/PacketNumberTest.cpp.o
[ 16%] Building CXX object quic/handshake/test/CMakeFiles/FizzPacketNumberCipherTest.dir/FizzPacketNumberCipherTest.cpp.o
[ 16%] Building CXX object quic/codec/test/CMakeFiles/QuicConnectionIdTest.dir///common/test/TestMain.cpp.o
[ 17%] Linking CXX executable QuicConnectionIdTest
[ 17%] Building CXX object quic/codec/test/CMakeFiles/QuicIntegerTest.dir///common/test/TestMain.cpp.o
[ 17%] Built target QuicConnectionIdTest
[ 18%] Building CXX object quic/handshake/test/CMakeFiles/FizzPacketNumberCipherTest.dir///common/test/TestMain.cpp.o
[ 19%] Building CXX object quic/codec/test/CMakeFiles/PacketNumberTest.dir///common/test/TestMain.cpp.o
[ 20%] Linking CXX executable QuicIntegerTest
[ 21%] Built target mvfst_codec
[ 21%] Building CXX object quic/state/CMakeFiles/mvfst_state_machine.dir/StateData.cpp.o
[ 21%] Linking CXX executable PacketNumberTest
[ 21%] Built target QuicIntegerTest
[ 22%] Building CXX object quic/state/CMakeFiles/mvfst_state_machine.dir/PendingPathRateLimiter.cpp.o
[ 22%] Linking CXX executable FizzPacketNumberCipherTest
[ 22%] Built target PacketNumberTest
[ 22%] Built target FizzPacketNumberCipherTest
/home/h3c/ywc/mvfst/quic/state/StateData.cpp: In member function ‘bool quic::QuicConnectionStateBase::retireAndSwitchPeerConnectionIds()’:
/home/h3c/ywc/mvfst/quic/state/StateData.cpp:161:22: error: could not convert ‘((quic::QuicConnectionStateBase*)this)->quic::QuicConnectionStateBase::nodeType’ from ‘quic::QuicNodeType’ to ‘bool’
auto& mainPeerId = nodeType == QuicNodeType::Client ? serverConnectionId
^
quic/state/CMakeFiles/mvfst_state_machine.dir/build.make:110: recipe for target 'quic/state/CMakeFiles/mvfst_state_machine.dir/StateData.cpp.o' failed
make[2]: *** [quic/state/CMakeFiles/mvfst_state_machine.dir/StateData.cpp.o] Error 1
CMakeFiles/Makefile2:4426: recipe for target 'quic/state/CMakeFiles/mvfst_state_machine.dir/all' failed
make[1]: *** [quic/state/CMakeFiles/mvfst_state_machine.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yangchi** [comment]
This is such a strange error though. == has higher precedence than = and ?=. Then after that, ?= goes first since = and ?= are same precedence and right-to-left associativity.

What compiler is this?

**Comment by yangchi** [comment]
OK i'm trying this on my WSL today

**Comment by yangchi** [comment]
Well at least on a WSL Ubuntu, it builds fine.
@weiyuxingchen Can you pull latest, delete the _build dir and try again, or at least let me know what compiler you use?

**Comment by zInPython** [comment]
@yangchi I got the same error with the newest codes on Centos 7.5 . I used gcc/g++ 5.3.0，cmake 3.10 . Details：
==============================
[root@localhost mvfst]# cd mbuild/
[root@localhost mbuild]# ls
CMakeCache.txt  CMakeFiles  cmake_install.cmake  Makefile  mvfst-config.cmake  quic
[root@localhost mbuild]# make -j4
[  1%] Built target mvfst_bufutil
[  3%] Built target mvfst_constants
[  5%] Built target mvfst_exception
[  8%] Built target mvfst_looper
[ 14%] Built target mvfst_codec_types
[ 16%] Built target mvfst_codec_decode
[ 18%] Built target mvfst_codec_packet_number_cipher
[ 26%] Built target mvfst_handshake
[ 28%] Built target mvfst_codec_pktbuilder
[ 32%] Built target mvfst_codec
[ 33%] Building CXX object quic/state/CMakeFiles/mvfst_state_machine.dir/StateData.cpp.o
/home/h3c/ywc/mvfst/quic/state/StateData.cpp: 在成员函数‘bool quic::QuicConnectionStateBase::retireAndSwitchPeerConnectionIds()’中:
/home/h3c/ywc/mvfst/quic/state/StateData.cpp:161:22: 错误：could not convert ‘((quic::QuicConnectionStateBase*)this)->quic::QuicConnectionStateBase::nodeType’ from ‘quic::QuicNodeType’ to ‘bool’
   auto& mainPeerId = nodeType == QuicNodeType::Client ? serverConnectionId
                      ^
make[2]: *** [quic/state/CMakeFiles/mvfst_state_machine.dir/StateData.cpp.o] 错误 1
make[1]: *** [quic/state/CMakeFiles/mvfst_state_machine.dir/all] 错误 2
make: *** [all] 错误 2
[root@localhost mbuild]# 
[root@localhost mbuild]# gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/5.3.0/lto-wrapper
目标：x86_64-unknown-linux-gnu
配置为：/usr/local/src/gcc-5.3.0/configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
线程模型：posix
gcc 版本 5.3.0 (GCC)

**Comment by weiyuxingchen** [comment]
@yangchi  thanks for your reply.
The compiler I use is gcc5.4.0. There will be many syntax errors, but I have tried to avoid them. Now the problems have been solved. Thank you again！
