### ISSUE TITLE
function updateRtt confusion

### ISSUE THREAD

**Issue by LyraWang** [facebookincubator/mvfst#77]
void updateRtt(
    QuicConnectionStateBase& conn,
    std::chrono::microseconds rttSample,
    std::chrono::microseconds ackDelay) {
  std::chrono::microseconds minRtt = timeMin(conn.lossState.mrtt, rttSample);
  conn.lossState.maxAckDelay = timeMax(conn.lossState.maxAckDelay, ackDelay);
  bool shouldUseAckDelay = (rttSample > ackDelay) &&
      (rttSample > minRtt + ackDelay || conn.lossState.mrtt == kDefaultMinRtt);
  if (shouldUseAckDelay) {
    rttSample -= ackDelay;
  }
  conn.lossState.mrtt = minRtt;
  // We use the original minRtt without the ack delay included here
  // explicitly. We might want to change this by including ackDelay
  // as well.
  conn.lossState.lrtt = rttSample;
  ...
}

Hello, the above code was from quic/state/QuicStateFuncion.cpp updateRtt(). It seems the minRtt always contains the ackdelay, while to the lrtt the ackdelay is not always contained. I'm confused about this settings .

According to your comments, should I change the code in following way?
std::chrono::microseconds minRtt = timeMin(conn.lossState.mrtt, rttSample);   
==>std::chrono::microseconds minRtt = timeMin(conn.lossState.mrtt, rttSample - ackDelay);   

Else if I want ackDelay always been contained, I should  let "shouldUseAckDelay " always be false.

I don't know if I misunderstand this code，looking forward to your reply,  thank you very much.

**Comment by yangchi** [comment]
That is correct. See A.6 in the recovery draft: https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#name-on-receiving-an-acknowledgm

We should probably add a comment there as well just like the draft so people no longer gets confused about this.

**Comment by yangchi** [comment]
I added comments in https://github.com/facebookincubator/mvfst/commit/b966acfca66cffed8a0fcb2f6f3ac1cc4a25eda2
