### ISSUE TITLE
ConnectionError of tperf.cpp

### ISSUE THREAD

**Issue by Enjia** [facebookincubator/mvfst#82]
I modified tperf.cpp and after that client can send data to server successfully
However when it implied connection end after sending all data the client threw an error：“[EventHandler.cpp:89] EventBase:failed to register event for fd 8:Resources temporarily unavailable”. Then server also threw an error:“[tperf.cpp] Socket error=Internal error” which triggered onConnectionError

So I wonder the possible reasons leading to such error? Because data is sent successfully, can I just ignore the error?
Thanks!

**Comment by udippant** [comment]
This error typically means that you've run into the some limits, such as memories, processes (if you are `fork()ing` or open 'file-descriptor' limits (more likely if you have lots of sockets open).
You can check the thresholds locally via `ulimit -a`

Can you share more details about your setup?

**Comment by Enjia** [comment]
I just run the following code:
`class TPerfClient : public quic::QuicSocket::ConnectionCallback,
                    public quic::QuicSocket::ReadCallback,
                    public quic::QuicSocket::WriteCallback,
                    public quic::QuicSocket::DeliveryCallback
{
  public:
    QuicClient(const std::string& host, u16 port): addr(host.c_str(), port), networkThread("CCPerfClientThread") {
        this->evb = networkThread.getEventBase();
    }
    std::future<int> connect() {
        this->evb->runInEventBaseThreadAndWait([&] {
            auto sock = std::make_unique<folly::AsyncUDPSocket>(evb);
            quicClient =
                std::make_shared<quic::QuicClientTransport>(evb, std::move(sock));
            quicClient->setHostname("echo.com");
            quicClient->setCertificateVerifier(
                quic::test::createTestCertificateVerifier()
            );
            quicClient->addNewPeerAddress(addr);

            LOG(INFO) << "CCPerfMvfst connecting to " << addr.describe();
            quicClient->start(this);
        });
        return transportReady.get_future();
    }
/* codes */
}
void do_client() {
    auto client = TperfClient(FLAGS_ip, FLAGS_port);
    auto ready = client.connect();
    ready.wait();
    **// do nothing, just wait**
}
int main(int argc, char **argv) {
    gflags::ParseCommandLineFlags(&argc, &argv, false);
    folly::Init init(&argc, &argv);
    fizz::CryptoUtils::init();

    if (FLAGS_mode == "client") {
        do_client();
    } else {
        do_server();
    }
    return 0;
}
`
Those codes just finished connection without transferring any data.
After running these codes, the print message is:
TPerfClient connecting to [::1]:6668
TPerfClient: onTransportReady
TPerfClient connection end
EventBase: failed to register event handler for fd 8: Resource temporarily unavailable

**Comment by Enjia** [comment]
I just run the following code:
`class TPerfClient : public quic::QuicSocket::ConnectionCallback,
public quic::QuicSocket::ReadCallback,
public quic::QuicSocket::WriteCallback,
public quic::QuicSocket::DeliveryCallback
{
public:
QuicClient(const std::string& host, u16 port): addr(host.c_str(), port), networkThread("CCPerfClientThread") {
this->evb = networkThread.getEventBase();
}
std::future connect() {
this->evb->runInEventBaseThreadAndWait([&] {
auto sock = std::make_uniquefolly::AsyncUDPSocket(evb);
quicClient =
std::make_sharedquic::QuicClientTransport(evb, std::move(sock));
quicClient->setHostname("echo.com");
quicClient->setCertificateVerifier(
quic::test::createTestCertificateVerifier()
);
quicClient->addNewPeerAddress(addr);

        LOG(INFO) << "CCPerfMvfst connecting to " << addr.describe();
        quicClient->start(this);
    });
    return transportReady.get_future();
}
other unrelevant codes
}
void do_client() {
auto client = TperfClient(FLAGS_ip, FLAGS_port);
auto ready = client.connect();
ready.wait();
// do nothing, just wait
}
int main(int argc, char **argv) {
gflags::ParseCommandLineFlags(&argc, &argv, false);
folly::Init init(&argc, &argv);
fizz::CryptoUtils::init();

if (FLAGS_mode == "client") {
    do_client();
} else {
    do_server();
}
return 0;
}
`
Those codes just finished connection without transferring any data.
After running these codes, the print message is:
TPerfClient connecting to [::1]:6668
TPerfClient: onTransportReady
TPerfClient connection end
EventBase: failed to register event handler for fd 8: Resource temporarily unavailable

**Comment by Enjia** [comment]
I just run the following code:
`class TPerfClient : public quic::QuicSocket::ConnectionCallback,
public quic::QuicSocket::ReadCallback,
public quic::QuicSocket::WriteCallback,
public quic::QuicSocket::DeliveryCallback
{
public:
QuicClient(const std::string& host, u16 port): addr(host.c_str(), port), networkThread("CCPerfClientThread") {
this->evb = networkThread.getEventBase();
}
std::future connect() {
this->evb->runInEventBaseThreadAndWait([&] {
auto sock = std::make_uniquefolly::AsyncUDPSocket(evb);
quicClient =
std::make_sharedquic::QuicClientTransport(evb, std::move(sock));
quicClient->setHostname("echo.com");
quicClient->setCertificateVerifier(
quic::test::createTestCertificateVerifier()
);
quicClient->addNewPeerAddress(addr);
LOG(INFO) << "CCPerfMvfst connecting to " << addr.describe();
    quicClient->start(this);
});
return transportReady.get_future();
}
other unrelevant codes
}
void do_client() {
auto client = TperfClient(FLAGS_ip, FLAGS_port);
auto ready = client.connect();
ready.wait();
// do nothing, just wait
}
int main(int argc, char **argv) {
gflags::ParseCommandLineFlags(&argc, &argv, false);
folly::Init init(&argc, &argv);
fizz::CryptoUtils::init();

if (FLAGS_mode == "client") {
do_client();
} else {
do_server();
}
return 0;
}`
Those codes just finished connection without transferring any data.
After running these codes, the print message is:
TPerfClient connecting to [::1]:6668
TPerfClient: onTransportReady
TPerfClient connection end
EventBase: failed to register event handler for fd 8: Resource temporarily unavailable

**Comment by udippant** [comment]
I do not see anything obvious from the code you shared.

Are both the sever and client on the same host? If so, can you share what's in the do_server() as well?

Also, can you run client and server with increased VLOG verbosity (e.g. --v=4) and share the logs?

**Comment by Enjia** [comment]
./tperf -mode=client **-v=4**
I0111 13:56:23.999944 13447 tperf.cpp:481] TPerfClient connecting to [::1]:6666
I0111 13:56:24.000385 13447 QuicPacketScheduler.cpp:473] Wrote crypto frame offset=0 bytesWritten=232 client CID=cdaa52ec9f9364d1 server CID=None peer address=[::1]:6666
I0111 13:56:24.003458 13447 tperf.cpp:413] TPerfClient: onTransportReady
I0111 13:56:24.003489 13447 QuicPacketScheduler.cpp:473] Wrote crypto frame offset=0 bytesWritten=36 client CID=cdaa52ec9f9364d1 server CID=400002006aaab5d3 peer address=[::1]:6666
I0111 13:56:24.003712 13447 QuicClientTransport.cpp:314] Client received ack for largestAcked=0 client CID=cdaa52ec9f9364d1 server CID=400002006aaab5d3 peer address=[::1]:6666
I0111 13:57:24.004668 13447 QuicTransportBase.cpp:2121] idleTimeoutExpired client CID=cdaa52ec9f9364d1 server CID=400002006aaab5d3 peer address=[::1]:6666
I0111 13:57:24.004737 13447 QuicTransportBase.cpp:2263] Clearing 0 peek callbacks
I0111 13:57:24.004752 13447 tperf.cpp:423] TPerfClient connection end
E0111 13:57:24.006814 13447 EventHandler.cpp:89] EventBase: failed to register event handler for fd 8: Resource temporarily unavailable







**-v=10** 

I0111 13:55:14.256525 13413 QuicTransportBase.cpp:2121] idleTimeoutExpired client CID=d1e0a9f5bc2f1ffb server CID=40000148c6e0eca8 peer address=[::1]:6666
I0111 13:55:14.256593 13413 QuicTransportBase.cpp:329] Stopping read looper due to immediate close client CID=d1e0a9f5bc2f1ffb server CID=40000148c6e0eca8 peer address=[::1]:6666
I0111 13:55:14.256609 13413 FunctionLooper.cpp:84] stop: ReadLooper
I0111 13:55:14.256623 13413 FunctionLooper.cpp:84] stop: PeekLooper
I0111 13:55:14.256631 13413 FunctionLooper.cpp:84] stop: WriteLooper
I0111 13:55:14.256644 13413 QuicTransportBase.cpp:2263] Clearing 0 peek callbacks
I0111 13:55:14.256656 13413 QuicTransportBase.cpp:772] Stopping read looper client CID=d1e0a9f5bc2f1ffb server CID=40000148c6e0eca8 peer address=[::1]:6666
I0111 13:55:14.256670 13413 FunctionLooper.cpp:84] stop: ReadLooper
I0111 13:55:14.256682 13413 QuicTransportBase.cpp:1094] Stopping peek looper client CID=d1e0a9f5bc2f1ffb server CID=40000148c6e0eca8 peer address=[::1]:6666
I0111 13:55:14.256695 13413 FunctionLooper.cpp:84] stop: PeekLooper
I0111 13:55:14.256706 13413 QuicTransportBase.cpp:1131] Client stopping write looper because conn closed client CID=d1e0a9f5bc2f1ffb server CID=40000148c6e0eca8 peer address=[::1]:6666
I0111 13:55:14.256721 13413 FunctionLooper.cpp:84] stop: WriteLooper
I0111 13:55:14.256732 13413 tperf.cpp:423] TPerfClient connection end
I0111 13:55:14.256743 13413 EventBase.cpp:572] EventBase(): Received terminateLoopSoon() command.
I0111 13:55:14.256772 13413 EventBase.cpp:497] EventBase(): Done with loop.
I0111 13:55:14.258798 13413 EventBase.cpp:258] EventBase(): Destroyed.
E0111 13:55:14.258832 13413 EventHandler.cpp:89] EventBase: failed to register event handler for fd 8: Resource temporarily unavailable
I0111 13:55:14.258874 13413 QuicClientTransport.cpp:78] Destroyed connection to server=[::1]:6666
--------------------------------------------------------------------------------------------------------
void do_server(){
	    TPerfServer server(
        FLAGS_host,
        FLAGS_port,
        FLAGS_block_size,
        FLAGS_writes_per_loop,
        flagsToCongestionControlType(FLAGS_congestion),
        FLAGS_gso,
        FLAGS_max_cwnd_mss,
        FLAGS_pacing,
        FLAGS_num_streams,
        FLAGS_bytes_per_stream);
    server.start();
}

**Comment by Enjia** [comment]
BTW, I dislodge the function createNewStream() in tperf.cpp, and in the same machine command ./tperf as well as ./tperf -mode=client were connected successfully, after 1 minute it throw the error messages posted above with other codes unchanged

**Comment by siyengar** [comment]
It looks like all your conns are hitting idle timeout and closing automatically. From the logs it doesn’t look like any data is sent. It might be possible that you have a lot of processes that are hanging around from previous tests. What would be more useful here is to fork the repo and check in your code into a branch of the fork. That way we can see the entire code in a formatted way. It’s hard to read a paste of the code, thanks

**Comment by Enjia** [comment]
Thanks, I think it is the folly that causes the problems. Because when I replace the newest folly repo with  old version folly repo, the codes run successfully and there's no errors

**Comment by udippant** [comment]
Sorry for not following up on this. 

Do you still see this issue?

**Comment by hanidamlaj** [comment]
Closing this issue for now, please feel free to re-open if this issue is still occurring.
