### ISSUE TITLE
Building project on Windows with error "mvfst_server.vcxproj" -- FAILED

### ISSUE THREAD

**Issue by z6833** [facebookincubator/mvfst#85]
I tried to compile the `mvfst` on windows with `cmake` and `visual studio` . And I used projects `vcpkg` ([URL to Vcpkg])(https://github.com/Microsoft/vcpkg#vcpkg) to install dependencies like `folly`, `fizz` and `others` .
 I can get other components done except `mvfst_server` and `mvfst_client` with following information:

29>Generating Code...
29>Done building project "mvfst_server.vcxproj" -- FAILED.
30>------ Rebuild All started: Project: ALL_BUILD, Configuration: Debug x64 ------
30>Building Custom Rule D:/zhao/mvfst/CMakeLists.txt
========== Rebuild All: 28 succeeded, 2 failed, 0 skipped ==========

 Detail logs:
[Output-Build.txt](https://github.com/facebookincubator/mvfst/files/4063808/Output-Build.txt)

Environment for building:
system : win7
VC : Visual Studio 2019
cmake : 3.16.2
vcpkg : latest

Is there any advice for the errors ?Or for building mvfst on windows7 ?
Thanks so much .

**Comment by yangchi** [comment]
you need to pull the latest fizz. Your mvfst is at the revision where some variant types in Fizz is supposed to be our home-baked variant but your fizz repo is still at a revision where these variants are boost::variant

**Comment by yangchi** [comment]
@z6833 : can you pull latest fizz and try again and let me know if you still see build errors? Thanks

**Comment by z6833** [comment]
Embarrassing...Yeah，I tried  . I just have something wrong with building fizz on Windows. I'm trying...

**Comment by yangchi** [comment]
I'm gonna close this for now. Feel free to reopen if you still have build errors after pulling the latest fizz.
