### ISSUE TITLE
How to compile as a so library on Android？

### ISSUE THREAD

**Issue by luoheng158** [facebookincubator/mvfst#99]
I want develop an android app use QUIC. Can you tell me how to compile as a so library on Android? thank you very much.

**Comment by yangchi** [comment]
There are Android tutorialson how to use C++ libraries on Android. For example, here is the official Android doc on this topic: https://developer.android.com/studio/projects/add-native-code. It seems quite detailed and easy to follow.

The Cmake files we provided in our repo, however, doesn't serve this purpose. I don't think Cmake files in the open source Fizz and Folly repos have such support either. You will need to make your own cmake files for these 3 repo (and possibly other dependencies that's in c++ and doesn't have a prebuilt object file).

Inside Facebook we use BUCK as our build tool. The BUCK file that supports Android build isn't included in this repo, and likely won't be any time soon given it's quite customized to our way of using this library on Android.

I'm also very hesitant to provide a prebuilt object file for Mvfst. You will still need fizz and folly. Plus we don't have the time and resource to keep it updated. I'd recomment just follow the Android tutorial I linked above.

To have proper Quic support in your Android app, you will need more than just Mvfst. The integration layer needs to handle Quic falling back to TCP or race both Quic and TCP connection properly. See previous issue on mobile support in https://github.com/facebookincubator/mvfst/issues/31.
